### ISSUE TITLE
Start api in vscode failed when run vscode tests

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-dev#1028]
**Describe the issue:**
Start api in vscode failed when run vscode tests.

**Repro Steps:**
1. Run `bash ./test-templates.sh -t <template_name>  -b staging  -c false`
2. Open the project in VS Code
3. Hit F1, Run Task, Start API and Web

**Error Message:**

> todo-csharp-sql-swa-func

![GetImage (33)](https://user-images.githubusercontent.com/20970631/198565978-b491dfb6-1b9c-4fe4-aa9b-7c513436d0da.png)

> todo-python-mongo-swa-func

![image](https://user-images.githubusercontent.com/57166602/198964726-67841635-41aa-42c1-8664-098def40075e.png)

**Environment:**
- 1.Windows: 
  https://github.com/Azure-Samples/todo-csharp-sql-swa-func
  https://github.com/azure-samples/todo-python-mongo-swa-func 
  2.Linux: 
  https://github.com/Azure-Samples/todo-csharp-sql-swa-func
  https://github.com/azure-samples/todo-python-mongo-swa-func 
  3.Dev container in VS Code:
  https://github.com/azure-samples/todo-python-mongo-swa-func 
  https://github.com/azure-samples/todo-python-mongo
  https://github.com/azure-samples/todo-python-mongo-aca
- Branch: staging
- Azd version: 0.3.0-beta.6-daily.1947218 (commit e20ee4e6819f464f1f19d768d62bfaef493d46d8)

**Expected behavior:**
Start api in vscode successfully when run vscode tests.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@zzhxiaofeng Was this working in our previous releases?

@philliphoff @karolz-ms any recent changes we made w.r.t to this causing to regress? Let us know if this is a blocker for Nov 2nd release.

**Comment by philliphoff** [comment]
I'm not seeing the same issue.  (My `func` installation is not working at the moment so I can't say it's successfully started but VS Code is able to find the task to *try* to start it.)

@zzhxiaofeng Is the AZD extension installed (and which build)?  Does the `tasks.json` generated by the template have the `API Functions Run` task?

**Comment by karolz-ms** [comment]
@zzhxiaofeng what is the exact template that you used for this test? I assume `csharp-sql-swa-func`, because from looking into what is in the `main` branch, that is the only template that has [`API Functions Run` task defined](https://github.com/Azure/azure-dev/blob/main/templates/todo/projects/csharp-sql-swa-func/.vscode/tasks.json#L43). If you are getting this error when testing other templates, something is wrong/mixed up with the workspaces/VS Code files that you are using for testing. 

My bet is because you omit the cleanup after test (`-c false`) you ended up with a workspace containing files from more than one AZD template. Try running the test with `-c` option. @rajeshkamal5050  we might want to change the test script to do local folder cleanup every time, regardless of the value of the `-c` option.

@zzhxiaofeng I am also not sure what is the `staging` branch that you refer to. There is no staging branch in the AZD GH repo as far as I can tell.

@madebygps FYI. Not exactly sure what went wrong here but like I said above, my money is on insufficient cleanup during testing, see above. The `tasks.json` in the template you authored seems fine.

**Comment by zedy-wj** [comment]
@rajeshkamal5050 , @philliphoff , @karolz-ms - We reinstalled the [Azure Functions Core Tools (4+)](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Clinux%2Ccsharp%2Cportal%2Cbash) and reinstalled the Azure Functions in the vscode extension. After testing again, this issue no longer reproduces under these templates and environments. But` todo-python-mongo-swa-func` template has new problems in the `devcontainer` environment, this is our new issue:https://github.com/Azure/azure-dev/issues/1057 , please review it.
