### ISSUE TITLE
[Issue] `azd init` requires `sudo` as a result of needing to open azd configuration file on Ubuntu

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1041]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 0.3.0-beta.6-pr.1947047 (commit 3081f88df499275126fda40feff9ac155daad18a)`

**Output from `az version`** 
```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```
**Describe the bug**
On Ubuntu 20.04 (WSL), I need to run init with sudo in order for azd to be able to open the configuration file. 
![image](https://user-images.githubusercontent.com/8949415/199051522-8fb81edc-b9a7-468f-bd84-129d931f50c3.png)

**To Reproduce**
1. Create new directory
2. Run azd init (with or without a template)
3. Get permission denied
4. Run again with `sudo` or `sudo !!`
5. Now command will run correctly.

**Comment by savannahostrowski** [comment]
To be more clear, sudo is required for **every** config command. 

![image](https://user-images.githubusercontent.com/8949415/199052793-93f8bce8-a822-4e31-8ab9-9d299214a9a2.png)

**Comment by rajeshkamal5050** [comment]
@vhvb1989 any updates on reproducing this on your side??

**Comment by vhvb1989** [comment]
could not repro using VSCode to connect to a Linux20.04 VM.
Trying in wsl next

**Comment by vhvb1989** [comment]
reproduced on WSL, directly launching wsl from console

**Comment by vhvb1989** [comment]
Found out that the happens when the `.azd ` folder has been previously created.  And it was created with read only access

![image](https://user-images.githubusercontent.com/24213737/199113603-cf3efbc8-28ff-4a86-9498-2ef6a9f46337.png)

Before `azd version = azure-dev-cli_0.2.0-beta.1`, azd would crete `.azd` folder with `drw-r--r--` access.
So, this issue impacts any customer who used this version (or any version before that) on any Linux set-up (WSL, ssh-remote, devcontainer, etc), as they already have a folder `.azd` with read only mode, which will cause the issue.

We have 2 options:
1. The easiest.  Document this behavior and tell any customer who faces it to manually delete `.azd` folder ( rm -r ~/.azd ).  Then they can run `azd` and the issue would be gone. (azd would create the folder again with the right access).
2. The more complicated. We need to add a check in code to see if the folder is read-only and if yes, update it.

your call @rajeshkamal5050 .   I would think that option 1 is better, easier and with no potential new-issues added after adding the code to detect and do the patching.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 
- Thanks for triaging and finding the root cause. I think we should be fine documenting it. 
- Can you work with @puicchan in documenting it?

@savannahostrowski 
- Can you try running using option 1(from a clean slate)?
- Removing blocker and adding to documentation. Let us know if you think otherwise.

**Comment by savannahostrowski** [comment]
We're good to go - thanks for investigating @vhvb1989! Let's definitely document this but deleting the directory worked for me!

**Comment by rajeshkamal5050** [comment]
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot#azd-init-requires-sudo
