### ISSUE TITLE
Allow `azd env refresh` against an environment that doesn't exist locally

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#11]
I cloned a project that doesn't have an .azure folder yet.

I want to pull the environment info down.

I run `azd env refresh -e envname` expecting it to prompt for me to select a sub to pull the env from.

But instead I get this:

```
Error: no project exists; to create a new project, run `azd init`.
```

I'd expect it to let me select a sub and continue with the refresh.

**Comment by vhvb1989** [comment]
@jongio , the error you are getting is because your project doesn't have `azure.yaml` in the root (so the folder is not considered an azd project)

Would you like to make `azd env refresh` to create an empty `azure.yaml` file if it is not there?

**Comment by jongio** [comment]
Repro:

1. `gh repo clone Azure-Samples/todo-nodejs-mongo` (it has azure.yaml)
2. `azd env refresh`

get:
Error: no project exists; to create a new project, run `azd init`.

I would prefer to not have to init a project.

I expect it to prompt me for the environment name and then refresh versus ask me to init a new project.

**Comment by vhvb1989** [comment]
@jongio did you `cd todo-nodejs-mongo` after step 1 ??   Otherwise I can't reproduce what you are seeing.

I do
1.	gh repo clone Azure-Samples/todo-nodejs-mongo 
2.    cd todo-nodejs-mongo
3.    azd env refresh

Then it asks for env name:

![image](https://user-images.githubusercontent.com/24213737/178872499-aa93c604-684b-4ba9-8ecc-3d65d27b2b45.png)

The error you are seeing is when `azure.yaml` is not found in the directory where you are running `azd`,  So, can you share more info about the path you are using?   

I will try to repro on Windows... just in casa

**Comment by vhvb1989** [comment]
tried in Windows as well..  the only way to reproduce is by not doing `cd todo-nodejs-mongo` which would be expected.
@jongio please review

**Comment by jongio** [comment]
Okay, it works as expected if I cd to the dir.
