### ISSUE TITLE
[devcontainer] "API dotnet run" task failed in the vscode.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1101]
**Describe the issue:**
`API dotnet run` task failed in the vscode.

**Repro Steps:**
1. Open the project in VS Code.
2. Hit F1, Run Task, Start API and Web. you will get the error: `uriString cannot be null` in the `API dotnet run`. Then, replace the `builder.Configuration["AZURE_COSMOS_ENDPOINT"]` in the api `program.cs` file with the actual value. 
![image](https://user-images.githubusercontent.com/57166602/201046075-03ac00a0-e88d-48df-8db4-1662375e81e3.png)
![image](https://user-images.githubusercontent.com/81678720/200496343-e8d2faae-d5bd-403c-90a7-3f2717c69ef4.png)

4. Hit F1, Run Task, Start API and Web again. Let the app start. Later you will see the error as below:
![image](https://user-images.githubusercontent.com/81678720/200286468-5273b237-060f-4234-bf74-956848eb5b49.png)

**Environment:**
OS: devcontainer.
Template: https://github.com/azure-samples/todo-csharp-cosmos-sql 
azd version: 0.4.0-beta.1-daily.1965526 (commit e2b43ea79ca6642946ae10227156cc5a88d861f2)
Branch: [pr/1087](https://github.com/Azure/azure-dev/pull/1087)

**Expected behavior:**
Task `API dotnet run` can run successfully.

@jongio , @rajeshkamal5050 for notification.

**Comment by zedy-wj** [comment]
This issue also occurs in other environments: 

- OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces

- Template: https://github.com/azure-samples/todo-csharp-cosmos-sql

- Azd version: 0.4.0-beta.1-pr.1988386 (commit https://github.com/Azure/azure-dev/commit/7b6248aa6788d586bcf0b9a9491187866dad5cca)

- Branch: [pr/1153](https://github.com/Azure/azure-dev/pull/1153)

**Comment by jongio** [comment]
Likely related to auth changes.

**Comment by karolz-ms** [comment]
> Likely related to auth changes.

Agreed. Probably not VS Code-specific.

**Comment by ellismg** [comment]
Taking a look...

**Comment by rajeshkamal5050** [comment]
@karolz-ms @bwateratmsft do you think the root-cause for this is the same as https://github.com/Azure/azure-dev/issues/1157#issuecomment-1315637798 ?

**Comment by ellismg** [comment]
> Hit F1, Run Task, Start API and Web. you will get the error: uriString cannot be null in the API dotnet run. Then, replace the builder.Configuration["AZURE_COSMOS_ENDPOINT"] in the api program.cs file with the actual value.

This problem shouldn't be related to the login changes - the template itself has a bug.  It should be exporting `AZURE_COSMOS_ENDPOINT` as an output because the application uses it when being run.

The second part is likely an auth issue and could be a fall out of the azd changes.  It seems like whatever principal the user is running as doesn't have permission granted to access the CosmosDB.  We may not be creating the RBAC permissions correctly as part of the template, or a different principal is being used to deploy the application from the one that is being used to run it.  I've fixed the first part and now I'm looking into the second.

**Comment by ellismg** [comment]
Interestingly enough, it seems like this template doesn't grant RBAC access to the user that deploys the template, and so it's not surprising that RBAC blocked access.  Azure is working as intended here.

I suspect that both of these issues have been present for a while - we never saw them because they would only happen when running the application locally and trying to connect to cloud resources, which is not something we test today.  Testing against the version deployed in Azure would have worked because `AZURE_COSMOS_ENDPOINT` is being set as a property on the App Service and we grant the app service permission to use the CosmosDB.

**Comment by ellismg** [comment]
FWIW - this was not related to the auth changes at all.

**Comment by Andomeda83** [comment]
I've just ran into this issue from using the template yesterday (17th Nov 2022). I'm using `azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)`.

I *think* it's because #1161 hasn't made it to the template itself https://github.com/Azure-Samples/todo-csharp-cosmos-sql/blob/main/infra/main.bicep.

I *could* do `azd init -t Azure-Samples/todo-csharp-cosmos-sql -b pr/1161`, but I'm guessing there are other updates missing too.

Is there a way to get the latest template code from this repo?

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 Similar errors in the following cases:


- OS: Windows desktop and Linux desktop .
- Template: todo-csharp--cosmos-sql
- Branch: staging
- Azd version: 0.8.0-beta.3-daily.2763383  (commit https://github.com/Azure/azure-dev/commit/3f484a283b309b3cab6f91386a4a7af7f4a082a2)

Hit F1, Run Task, Start API and Web, error message as follow:
![image](https://github.com/Azure/azure-dev/assets/80496810/db51b61f-fd29-42bc-a91b-598b88fc8b28)
