### ISSUE TITLE
Azure CLI 2.x is not installed on the machine of azdo pipeline.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1158]
**Describe the issue:**
Azure CLI 2.x is not installed on the machine of azdo pipeline.

**Repro Steps:**

1. Open the project in VS Code.
2. Login with `azd login`.
3. Run command: `azd pipeline config --provider azdo`
4. Click on the link that is printed to open the actions page and you will see:
![image](https://user-images.githubusercontent.com/81678720/201892182-9ae38a1d-5432-4b80-ab71-f65cfc5a33a4.png)

**Environment:**
OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code
Template: All templates.
Branch: [pr/1153](https://github.com/Azure/azure-dev/pull/1153)
Azd version: 0.4.0-beta.1-pr.1988386 (commit https://github.com/Azure/azure-dev/commit/7b6248aa6788d586bcf0b9a9491187866dad5cca)

**Expected behavior:**
Action logs can pass successfully.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
Doesn't seem like a direct Azd -> Az CLI dependency. Looks like something underneath. @ellismg can you triage it?

**Comment by weikanglim** [comment]
It is due to the remaining usage of azure CLI authentication in Azure DevOps pipelines:

https://github.com/Azure/azure-dev/blob/d78120f18fa2b079e24db0b9a2da9b41e8cd64fe/templates/common/.azdo/pipelines/bicep/azure-dev.yml#L14-L17

Posted a comment to the [change](https://github.com/Azure/azure-dev/pull/1129/files#r1023088384)
