### ISSUE TITLE
[Python templates] Error on `deploy` after running the `api` server locally 

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1237]
Repro:
- azd init -t todo-python-mongo
- azd provision
- azd deploy
- VSCode-> Run Task -> Start API  (wait until the api is lauched)
- azd deploy:

![image](https://user-images.githubusercontent.com/24213737/205786143-0546cd49-7a4c-44bf-a897-285bfa3eeaba.png)

Root Cause:
When the `api` is launched locally, a new folder is created inside the `/api` folder called `api_env`.  This folder contains a virtual python environment where the application dependencies are installed and where the application is launched from.
Inside this folder, there are some folders which are `symLinks` to python binaries, like `lib64`:

![image](https://user-images.githubusercontent.com/24213737/205786608-60313e97-e1d2-408e-850a-697f7c9a3feb.png)

When `azd deploy`  runs, a zip file is created including all the content from `/api` folder, and the `create zip` implementation from `azd` does not support `symLinks` (it doesn't see it as a folder, but as a file, and failed to zip it).

As a workaround, before running `azd deploy`, we can delete the `api_env`.

Fix proposals:
1. Make `azd` to support excluding known folders while doing `deploy`. The `python` implementation, for example, should tell `azd` to ignore the `api_env` folder when doing `deploy`.  With this approach, we could also skip adding the `__pycache__` folders to the zip (those folders are created when running the app locally as well).
2. Use a temporal folder when running the app locally. For example `/temp/azdlocalrun/api_env`.
3. Use `azure.yaml` or an extra file (like `app.deploy.ignore`) to define files/folder which should not be zipped and deployed to Azure. This strategy would allow customers to have control over the deployment files without depending on `azd`
4. Combine option 1 and 3, where `azd` would have a hardcoded list of `ignore paths` and users can also extend the list with configuration files.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 was this working earlier? is this a regression due to Az CLI removal?

**Comment by v-xuto** [comment]
@rajeshkamal5050  When we were doing manul test according to **AzdManualTestPlan.docx**, we did not encounter this issue. Because the test scenarios are different. We did not execute `azd deploy` after `VSCode-> Run Task -> Start API`.

Our test scenario for executing `azd deploy` is as follows:
  1. azd init -t todo-python-mongo
  2. azd provision
  3. azd deploy
  4. Change “complete” to “completed” in UI 
  5. azd deploy

Besides, we ran the test and were able to reproduce this issue in **linux** VM. But, we also testing in **windows** and don't reproduce this issue.
- Azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
- Branch : main

**Comment by vhvb1989** [comment]
> @vhvb1989 was this working earlier? is this a regression due to any recent changes?
> 
> @v-xuto did you run into this issue?

Not a regression. This issue has been there since early versions (as it is within the zip strategy). 
It was just not yet discovered. (This means no one has been running the `api` server locally for python and later calling deploy after some changes to the code).

**Comment by rajeshkamal5050** [comment]
Similar bug on functions #1039

**Comment by pamelafox** [comment]
I would also like for azure.yaml to have an ignore/exclude mechanism. I was the one that reported that funcignore isn't being obeyed for functions, but now I'm in an App Service situation where I'm in need of a similar mechanism. I can't re-structure the code in this situation since I'm trying to add azd support to an existing project structure. Deploying is taking a very long time, since it's unnecessarily deploying the node_modules and venv directory.

**Comment by vhvb1989** [comment]
> stumbled

IIRC, shallow copy helps for files that are currently in use/locked.  The root cause here is copying files which should not be copied
