### ISSUE TITLE
Remove readme in /.azdo/pipelines/README.md in azd templates

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1313]
https://github.com/Azure-Samples/todo-nodejs-mongo/blob/main/.azdo/pipelines/README.md include the manual steps before azdo support is added to azd. We should remove from all azd templates.

**Comment by jongio** [comment]
That README is accurate and isn't the verbose version that it used to be.  I don't think it should be removed as it helps use the command.

**Comment by puicchan** [comment]
Is it diff from what's documented here? https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=azdo

**Comment by rajeshkamal5050** [comment]
Duplicate contents in ReadMe and in learn.microsoft. We can probably remove the ReadMe's.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 do we still need these pipeline readme's?

**Comment by vhvb1989** [comment]
My preference is when docs are part of the repo and used to produce any other external docs.
I would have the scr that is used for https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=azdo to be in Azure-dev repo, and use some sync mechanism to update the Microsoft docs repo.

Similar to what we do for generating the azd docs reference..

Since that's probably more work to do, for now, I would remove the docs from Azure-dev as mentioned in this issue and keep the one from Microsoft docs as the source of truth.

@puicchan , I would also like to have a link from MSDocs to this doc for steps on how to set up the pipeline manually and understand it better: https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/manual-pipeline-config.md

**Comment by savannahostrowski** [comment]
We've added this to the pre-GA docs plan. I've added @gkulin as a joint assignee on this issue.

@hemarina is there any remaining eng work needed here? If not, feel free to unassign yourself.

**Comment by savannahostrowski** [comment]
@hemarina Is this done now?

**Comment by savannahostrowski** [comment]
@gkulin anything left here?
