### ISSUE TITLE
ARM64 (Linux), Apple Silicon (M1, M2) support

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1314]
General issue to track addition support for AMR64 (Linux) and Apple Silicon (M1, M2, etc.) support. 

Current discussions involve our bar being: 
* Build client
* `azd` test suite passes
* Template tests pass

Current status: 
* We have access to a DevOps pool of ARM64 Linux machines but those machines are missing a lot of the software/tools needed for a successful build and run of test scenarios. Some can be [installed successfully with a script](https://gist.github.com/danieljurek/3e8fbc020eb9399a228cc6aa0d0b939d)
* ARM64 support in some tooling may not presently available so some services `azd` supports in x86_64 environments today will not work until support is added for those tools

**Comment by mex20** [comment]
I would also like to add that ```azd login``` fails to open the browser when running in a VS Code dev container that is running an x86_64 image with Rosetta emulation, by using the ```FROM --platform=amd64``` flag in the ```.devcontainer/Dockerfile```.  Therefore I am unable to log into ```azd```.

```azd login``` is unable to find the browser executable in $PATH as seen here:
![Screenshot 2023-01-06 at 12 51 07 PM](https://user-images.githubusercontent.com/12109514/213011974-b5649f9d-3e95-4201-823d-b644d1766548.png)



When I run ```az login``` I am able to successfully login, because the browser launches, which you can see here: 
<img width="1484" alt="Screenshot 2023-01-17 at 1 06 02 PM" src="https://user-images.githubusercontent.com/12109514/213013427-d4e0dd29-5ada-4c03-b84a-1d8f40b5935b.png">

I found this issue attempting to deploy [Aaron Powell's Azure-Remix-Stack v2](https://github.com/aaronpowell/azure-remix-stack/tree/v2), and the current workaround for Apple Silicon for the MCR images are what led me to this issue.

**Comment by pamelafox** [comment]
FYI, I've discovered that the docker-in-docker feature is not compatible with the --platform emulation flag: https://github.com/devcontainers/features/issues/219

So I believe that for local VS Code development, I can either have docker-in-docker support in my dev container, or azd support, but not both. Fortunately I think both should work in Codespaces since that's not running on an M1.

Additional motivation to have better ARM64 support.

**Comment by rajeshkamal5050** [comment]
@danieljurek has already captured,
- Details on how to get this working - https://github.com/Azure/azure-dev/issues/952#issuecomment-1338386205 with proper build, packaging and testing.
- Filed dependency issues 
  - Build/Pipeline dependency
     - https://github.com/microsoft/azure-pipelines-tasks/issues/17348 or https://github.com/microsoft/azure-pipelines-tasks/issues/17075
     - @danieljurek any other dependency we need for building and packaging?
  - Runtime dependency
     - https://github.com/microsoft/azure-pipelines-terraform/issues/116
     - @danieljurek remember you doing an exercise to go through the list of azd core and template level dependencies? Any other dependencies that doesn't have support?

**Comment by danieljurek** [comment]
Setting confidence to `Low` on this because automated validation scenarios like the ones we use for other binaries are not well covered at this time: 

* Little support in DevOps for Linux ARM scenarios 
* No support for Apple Silicon in DevOps 

If we just cross-compile then the process should be pretty simple to implement though we'd need to work on signing and installers. I'm not sure if signing macOS binaries compiled for ARM64 is supported.

**Comment by rajeshkamal5050** [comment]
@danieljurek agreed on trying to build, validate and test it natively on Linux ARM64 and Apple Silicon. Since ARM64 support and the ecosystem is not completely vetted and rolled out internally yet. It is definitely going to take sometime and might not be worth while to do the heavy lifting and custom building ourselves(azd and engsys) now.

Instead, as you said let us try to cross compile with our already existing pipelines/vm images. For now, this seems to be the  best approach we should take.
  - Let us start to internally build and release ARM64 bits.
  - Get some manual testing going(vendor, dev, CDA, internal users).
  - Once, we feel confident with our testing and flush out signing of bits.
  - We can release it.

cc: @savannahostrowski @Petermarcu @ellismg @weshaggard

**Comment by weshaggard** [comment]
Yes I think cross-compiling will be a reasonable starting point. I'll add that GitHub is targeting support for images in Q3 this year https://github.com/orgs/github/projects/4247?pane=issue&itemId=5944419 and which point we can hopefully leverage those to do building and testing on.

**Comment by Petermarcu** [comment]
I made this PR to update the docs to mention installing the emulator. https://github.com/MicrosoftDocs/azure-dev-docs/pull/1087

**Comment by rajeshkamal5050** [comment]
Moving this out to Gallium cc: @savannahostrowski

**Comment by pamelafox** [comment]
You probably already know this, but FYI that I'm unable to run the playwright tests for the TODO samples on my M1. There's a qemu error when it tries to start up Chromium. Just noting here as something affected by M1 usage.

**Comment by danieljurek** [comment]
This was released on 2023-10-05.
