### ISSUE TITLE
Tell people where to find msi

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1451]
Here: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=baremetal%2Cwindows

I don't see us telling the user where they can find the MSI.

Please include a link and give example `gh download` command.  

Thx

**Comment by danieljurek** [comment]
Because our repo has multiple entities in our GH releases (`azd` and the vscode plugin) the `gh release download` command won't work unless you specify the tag directly (e.g. `gh release download azure-dev-cli_0.5.0-beta.3 --pattern ...` 

If we didn't include the tag then in cases where the vscode extension is the most recent release then an MSI file will not be found.

**Comment by danieljurek** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4094

**Comment by jongio** [comment]
@danieljurek this works

```
gh release download --repo azure/azure-dev --pattern='azd-windows-amd64.msi'
```

**Comment by danieljurek** [comment]
> @danieljurek this works
> 
> ```
> gh release download --repo azure/azure-dev --pattern='azd-windows-amd64.msi'
> ```

Indeed, that does work at the moment because the most recently created release has a file which matches that pattern. When the latest release does not contain a matching file you'll get an error. Here's an example release of the vscode extension which doesn't have a file matching that pattern (we don't expect it to match in that case going forward): https://github.com/Azure/azure-dev/releases/tag/azure-dev-vscode_0.3.0

If we only had releases of the az CLI from our repo and had no release of the vscode extension then we could be confident that the command would work.

**Comment by rajeshkamal5050** [comment]
Thought we produce multiple artifacts from same repo. The installation and user workflows scenarios are distinct and optional. I believe this `gh release download --repo azure/azure-dev --pattern='azd-windows-amd64.msi'` should still be useful. Since,
- Azd CLI as a standalone is self-contained and folks use it without VS/VSCode.
- VS/VSCode is an integration aspect and has its own install procedure documented here - https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/debug?pivots=ide-vs-code.

**Comment by jongio** [comment]
ic, so because:

1. gh release download looks at most recent release
1. we ship vs code ext at a different cycle than the msi
1. the 'latest' release may not have an msi and the command would fail



The gh release download command does support the use of tags to get a download.

I'm wondering if we can find a creative way to use tags to get what we want...

For example:

If we always tag the latest msi release with 'msi-latest` and then use this command:

`gh release download msi-latest --repo azure/azure-dev --pattern='azd-windows-amd64.msi'`

Would that work?

**Comment by danieljurek** [comment]
Because `gh release` works off of releases and not tags, simply updating a tag does not get us back to a release in a single command. 

```pwsh
> git tag latest-a 361e5501b32b5b8e0e276438c81808ff75bcf4e0
> git push origin --tags
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:danieljurek/hypothetical-multi-project-repo.git
 * [new tag]         latest-a -> latest-a
> gh release download latest-a --repo danieljurek/hypothetical-multi-project-repo --pattern "pattern-a.txt"
release not found
```

However, it looks like [GitHub added the ability to set the latest release explicitly](https://github.blog/changelog/2022-10-21-explicitly-set-the-latest-release/) in October. If we use that feature, we can set the `latest` release to a CLI release and then the command without the tag does work. 

```pwsh 
> gh release download --repo danieljurek/hypothetical-multi-project-repo --pattern 'project-a.txt'
```

A couple of things need to happen to enable this: 

* All code which generates GitHub releases needs to ensure that the most recent CLI release is always marked `latest` 
* This only works for one product (i.e. the CLI and never the vscode extension or other future products from this repo)

I think these tradeoffs are reasonable at this point.

**Comment by danieljurek** [comment]
Opened an issue w/ GitHub CLI to discuss extending `gh release download` to include scenarios like this. 

The [docs](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=baremetal%2Cwindows) are updated with a link to the GitHub releases: 
![image](https://user-images.githubusercontent.com/2158838/216106653-4165fea4-afc6-4945-bab6-a82daef0bf72.png)
