### ISSUE TITLE
Using `todo` templates with Azure free trial subscription

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1460]
This issue is meant to define what's the experience for a customer when trying `azd` with a fresh new created [Azure Free trial subscription](https://azure.microsoft.com/en-us/free).

There are some settings defined on the `todo` templates, like the SKU for a service-plan which are only available on a specific `region` for a free trial subscription.  For example, trying to call `azd up -t todo-python-mongo` with the free trial sub and using the default Location `East US 2` would lead the users to an error like:

```
"code": "SubscriptionIsOverQuotaForSku",
"message": "This region has quota of 0 instances for your subscription. Try selecting different region or SKU."
```                

Then, switching to region `East US` works.  But, as a new customer, how do I know what region/settings to use when I am using the free trial?  Or how do I know which templates are 100% usable for my subscription?

--
Some ideas:

- consider creating templates with FREE sku options, as well as potentially adding a "tag" to the templates stating what the minimum Subscription type can be used i.e. FREE, Trial, Edu etc.

**Comment by puicchan** [comment]
Default region was selected because of capacity issue. Since we can't accurately predict/get the right region with capacity, my suggestion is to default to "east us" instead of "east us 2" to reduce issue for folks with free trial subscription.

**Comment by pamelafox** [comment]
Noting the experience from the workshop I ran, since it's related to this issue. In my workshop, they were trying to deploy https://github.com/pamelafox/simple-fastapi-azure-function to Azure Functions + APIM.

1) When they first tried azd up, they got: "ERROR: reading subscription id: please provide options to select from" As it turns out, they hadn't made a subscription. So I think it's really important for workshops to stress that folks need both an account and a subscription. I also think that error could be more newbie-friendly (I can file an issue for that- i.e. "If you don't yet have a subscription, you can create one in the portal.")

2) They then got a subscription, and I think they may have had to redo the auth login to get it to find the subscription ID. If thats the case, it might help to add an explicit instruction to above error message about that.

3) Then when they tried to up, they got this error: "Deployment Error Details:

Unauthorized: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

- This region has quota of 0 instances for your subscription. Try selecting different region or SKU." I haven't figured out which service was restricting them, so I wasn't sure what region to select. I did tell them how to find the .env file and change the location, but it might be annoying to try a bunch of locations. Not sure quite what to do about this. It'd be nice if it was easier to change location (something easier than digging for the .env file)

**Comment by savannahostrowski** [comment]
Related to #468; moving to Gallium as this is non-blocking for GA

**Comment by rajeshkamal5050** [comment]
@ellismg @vhvb1989 Explore validate API and see if it helps alleviating some of these issues?

**Comment by vhvb1989** [comment]
> validate API

The ValidateAPI checks the syntaxis. I don't think it would be able to help here:

> Validates whether the specified template is syntactically correct and will be accepted by Azure Resource Manager

https://learn.microsoft.com/en-us/rest/api/resources/deployments/validate.

Template's owner should know about any limitations (like region/sub/etc) and describe those limitations within the infra files (bicep).  
For example, using `@allowed` annotation to set what locations will work
