### ISSUE TITLE
Show prompt to install azd from vscode

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1461]
VS Code supports platform-specific extensions (see - https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions). As such, we should consider shipping our very small binary as part of the VS Code extension to streamline the getting started experience (azd is smaller than the Python language server ✨).

Today, we surface a prompt to the user in VS Code when we don't see azd in PATH and prompt the user to visit our DevHub install the tool.  We should still check to see if azd is already in PATH and use that if it's there but it'd be nice if we shipped a version of azd with the VS Code extension and installed it for them if we don't find it.

If we did this, we'd also need to release a new VSIX with our monthly release of azd core, which we don't do today.

**Comment by savannahostrowski** [comment]
@bwateratmsft Would love to know your thoughts here. Some of my inspiration here comes from other extensions like [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

**Comment by bwateratmsft** [comment]
It's doable, but I think there are some disadvantages. ESLint and Pylance are primarily (or entirely?) used only within the context of VSCode, whereas `azd` is meant to be usable both within and without (i.e. as a standalone CLI). I don't think it's appropriate for us to permanently alter the user's `PATH` environment variable, so the net result would be that terminals outside VSCode couldn't use the extension's copy of `azd`. If users wanted to do so they'd need to fully install `azd`, and that opens up the possibility for misbehavior due to the extension and the system having mismatching versions.

Another disadvantage is that, if ever we work out some way to function as a web extension, we'd want some way to avoid having to download it (because web extensions have to download ~every single time).

I think what might be a cleaner approach would be to offer a command in the extension to install `azd`, and if they try to do an action without `azd` installed, ask them if they want to run that command to do the installation. Having `azd` be fully installed means that any terminal on the system can use it, any updating strategy that we may use for `azd` is fully applicable (including auto-update if we add that), and it shows up in the Add/Remove Programs list.

We have a command like that in the Docker extension, although admittedly it doesn't work as cleanly since Docker Desktop installation is much more complicated (requires admin permissions, not as straightforward on Linux, requires certain Windows "Features" turned on, etc.). If `azd`'s installation is just simple file placement + environment variable updates, I don't think it will have any trouble here.

A disadvantage to the above install-based approach is that success of that command would be at the mercy of proxy and/or firewall settings, whereas if `azd` comes bundled, having the extension _at all_ would mean you have `azd` installed. Overall I don't think this is a widespread concern though. VS and VSCode have installed `vsdbg` via a PowerShell/Bash script downloading things for years now and it has only adversely affected a handful of users.

**Comment by savannahostrowski** [comment]
That's an interesting point re. in editor vs. outside the editor. Also great to know about the web scenario, I could see that coming down the pipe.

Another option is to surface something similar to what the [Go extension](https://marketplace.visualstudio.com/items?itemName=golang.Go) does. When the extension detects that a dependency is missing, it surfaces an "Analysis Tools Missing" warning, which the user can click on to download deps (see the GIF in their Quickstart section of the README). Thoughts on that? I'd be pretty content with this flow as it seems like a more transparent approach that doesn't feel super irritating or context switchy.

**Comment by savannahostrowski** [comment]
Could also have it as a command in the command palette in case someone misses the prompt and wants to do it at a later date.

**Comment by bwateratmsft** [comment]
We could proactively detect it but that may be overkill. IMO as long as we surface a notification if they try to _do_ anything, we're good.
