### ISSUE TITLE
Implement azd version in azure.yaml for backwards compat

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1504]
From team discussion:
- We will include azd version in azure.yaml to specify a range (use semantic versioning expressions - e.g. min/max)

_Originally posted by @savannahostrowski in https://github.com/Azure/azure-dev/issues/287#issuecomment-1400827181_

**Comment by Petermarcu** [comment]
Do you think the support in azure.yaml for min/max is a different feature than the CI/CD pinning feature? Or is the CI/CD pinning purely doc?

**Comment by ellismg** [comment]
> Do you think the support in azure.yaml for min/max is a different feature than the CI/CD pinning feature? Or is the CI/CD pinning purely doc?

I think these are separate things.  The first is a way for a template to express "I need this range of `azd` versions for me to work correctly".  I view this more as "I found some existing template and want to use it with `azd`, but it may require a newer version of `azd` because it uses some newer features".

For the second case, I view it more as "I want to ensure that when I'm running in CI, I use this exact version of `azd`, and that if the team releases a new version, I don't automatically upgrade".  I view this as "pin your dependencies" in CI story.

**Comment by rajeshkamal5050** [comment]
@ellismg is this change already in?
