### ISSUE TITLE
Provision/Deploy Failure Reason Telemetry/Analysis

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1539]
When we encounter a failure in a provision or deploy, we log it but we don't have clarity on whether this is user error, Azure upstream or azd proper. We need to investigate this.

**Comment by weikanglim** [comment]
@savannahostrowski @esweet431 

Is it enough that we have "Azure or service <Y> returned an error, the HTTP error code was <X>"? And if it wasn't an Azure or service error, it must have been an error on the client.

In the future, we can start expanding on types of client errors: prereq installs, but we need to do this in phases as it requires code restructuring.

Reasoning is as follows: classifying whether a user caused an error or not is quite a difficult problem, I just wanted to make sure we're not trying to create intelligence to guess this. If we did, we'll get false positives because we simply don't have enough information when the error occurs, so we'll need to think through how accurate this data is.

**Comment by savannahostrowski** [comment]
It'd be good to know
1. If it was an upstream error (and ideally, what it was so that we can bring the data to service teams)
2. If the error was an "us" issue (and ideally, with enough granularity that it can help us diagnose issues)
3. If it was a client issue (and ideally, what it was so that we can bring the data to client teams)
4. If it was a user error (malformed input, missing prereqs, etc)

**Comment by weikanglim** [comment]
Thinking through what that means for each **scenario**:

1. **Upstream services**. For service errors, we'll need to:
   - Set and log service correlation ID 
   - Log http status code
   - Give a developer-friendly identifier so we understand context. Logging any piece of the endpoint is problematic, and it may contain user data.
1. **Client tool dependencies**. For any external tool azd invokes, we'll need to:
   - Log exit code (unfortunately, this doesn't tell us a whole lot, generally non-zero exit codes simply means failure)
   - Log a translation of what that exit code meant (the developer should decide on this)
   - Log the client program name (no possible user data)
   - Log the developer-friendly invocation 
   - For programs that offer error types, we can integrate that. However, when errors are unstructured, we cannot log the error since it may contain user data
1. For remaining azd/user errors, the number of different possible errors are probably in ~1000, and `go` doesn't offer structured errors by default:
   - Log the callsite action
   - Log the error category
   - Log any useful error details we are able to get, with care taken to ensure no user data

@savannahostrowski , I like the framing in terms of diagnosis rather than immediate root-causing. From the categorization above, the initial spec on how we introduce error logging might take ~3-5 days. After that, logging for upstream is ~3 days, client tools is ~3days, and remaining azd/user errors is an unknown effort given that we have probably 100-1000+s of uncategorized errors (and not all of them should be categorized).

Based on that:

1. I think we should do service + client logging definitely before GA.
2. We should prioritize the biggest categories of azd errors. This could be things like `azd.tool.prereq` for tool prereq failures. The team can think through what this might mean, but we'll need to do this exercise separately before tackling these errors.

I do want to highlight that while the error categories and details might offer us some insights into where the error is, it might not always be the cause of error.

For example, if `azd` had done environment substitution on the bicep parameters file, and generated one that was invalid:
1. Bicep could have failed
2. Or Azure deployment could have failed

Let me know your thoughts on prioritization, and if what I mentioned about error cause vs. categorization for initial triage makes sense.

Added spec in 1499.

**Comment by savannahostrowski** [comment]
I think that makes sense. I suspect that any given category may have multiple "issues" to sort through. I don't view needed fixes as 1:1 with category. I also think that we could start with the categories above and then incrementally work through the uncategorized errors as we need/see fit. I'd say this is a "nice to have" for the May timeframe but can also come early next semester. Would be good if we could get it in so that we can see where folks are seeing failures as we hit critical mass.

@esweet431 might have additional thoughts here as well.

**Comment by weikanglim** [comment]
We offer service + tool error categorization with recent code changes. A dashboard has been set up with the changes, but I'll hold off on closing this to address remaining gaps.

**Comment by savannahostrowski** [comment]
Closing this for now as I think we are good until we identify gaps
