### ISSUE TITLE
Standardize on either `provision` or `infra create` in VSCode extension

### ISSUE THREAD

**Issue by bwateratmsft** [Azure/azure-dev#1563]
Originally from https://github.com/Azure/azure-dev/pull/853#discussion_r1091213418.

We use `provision` in some places and `infra create` in others. Ideally we should use only one of those.

**Comment by rajeshkamal5050** [comment]
@savannahostrowski Should we prefer keeping `azd provision` as public and remove/keep internal `azd infra create/delete`?

cc: @jongio

**Comment by savannahostrowski** [comment]
We have no equivalent for `infra delete` today, AFAIK. `azd down` covers the deprovisioning + tearing down deployments.

We should definitely stick with `provision` because that's what we promote. Perhaps we need a different command that feels more equivalent to `provision` as opposed to `infra delete`? `deprovision`? And then retire 	`infra create/delete`?

**Comment by bwateratmsft** [comment]
![image](https://user-images.githubusercontent.com/36966225/219728749-daded59c-0fdf-4eb8-a06c-7f958c15ad9e.png)

The robot overlords like "deprovision"

**Comment by rajeshkamal5050** [comment]
> We have no equivalent for infra delete today, AFAIK. azd down covers the deprovisioning + tearing down deployments.

Doesn't `azd infra delete` also behaves like `azd down`. If we are deleting/de-provisioning the infra aren't we implicitly pulling down deployments too?

**Comment by jongio** [comment]
I like deprovision

**Comment by savannahostrowski** [comment]
@weikanglim @rajeshkamal5050 This will be taken care of soon, JFYI. We should close this when changes are made.
