### ISSUE TITLE
[Issue] Add ability to export environment variables to GitHub Actions

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-dev#1597]
I want to refer to the output of variables in my bicep template in other parts of a Github action workflow.

e.g. use the generated name of the resource group, or the hostname of the web app service.

Currently, I can only export the outputs using the `azd env get-values` command which supports either dotenv or json as output.

dotenv is not compatible with GitHub's environment variables because all of the strings are quoted, e.g.,

```console
$ azd env get-values
AZURE_ENV_NAME="lt-webapp-demo"
...
```

If I pipe that to Github's [environment file](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) then all the variables include the quotes.

Please can we have an exporter that just formats `name=value` and doesn't quote the values so we can do:

```
azd env get-values --github >> $GITHUB_ENV
```

MY workaround is to pipe it through a double-sed command `azd env get-values | sed 's/="/=/' | sed 's/"$//'` to remove the leading and trailing quote.

**Comment by vhvb1989** [comment]
@tonybaloney , are you using `azd pipeline config` to create the github repo and have an initial github action flow?
Or are you manually creating repo+pipeline?

I am asking because It might make sense to update the `azd pipeline config` to automatically set all the values from azd-env into Github secrets, so you wouldn't need to manually export and set the variables for Github.

Would that work for you?  Let me know more about your scenario

**Comment by tonybaloney** [comment]
Yes that would be ideal. Would that work with any extra outputs at the bottom of main.bicep?

**Comment by markweitzel** [comment]
> Yes that would be ideal. Would that work with any extra outputs at the bottom of main.bicep?

We've hit a scenario where this would solve our issue as well.

**Comment by binderjoe** [comment]
I am hitting this also, and seems to be a mainstream scenario when working with more complex/real-world templates. Setting all of the environment variables and secrets is very cumbersome.
