### ISSUE TITLE
[install] azd requires root permissions to access /usr/local/bin

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-dev#1673]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**
When installing with `curl -fsSL https://aka.ms/install-azd.sh | bash` I get the message `install-azd: Writing to /usr/local/bin/ requires elevated permission. You may be prompted to enter credentials.` and prompted to use my password.

Problems: 
1. I don't know what the script does, and giving root credentials to an unknown bash script is not a good practice
2. Depending of the Linux distrib used, `/usr/local/bin` may not exist, as reported here: https://github.com/Azure/azure-dev/issues/1670
3. This doesn't give me any way to easily clean up what was installed

**To Reproduce**
Run `curl -fsSL https://aka.ms/install-azd.sh | bash` on any Unix system.

**Expected behavior**
Installation should occur in user folder, like most tools, with either a prompt to add the path to `$PATH` of detect `.bash_profile`, `.zshrc` or whatever and add it for you.

**Environment**
MacOS 12.6.3

**Comment by danieljurek** [comment]
@sinedied -- Thanks for opening an issue. I think we can make some documentation updates to help clarify things. 

Per-user installs are available today on MacOS [using `brew`](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=localinstall%2Cwindows%2Cbrew#install-using-package-management-tools). I'm going to update our READMEs 


The install script is meant to improve the user experience by following [patterns](https://www.man7.org/linux/man-pages/man7/hier.7.html) that are likely to result in the binary, by default, landing on a user's machine in a location which is already in `PATH`. This is so that `azd` will be found when calling from the user's shell. 

It's possible to specify a custom install location using the install script: 

```bash
curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --install-folder "~/custom-bin"
```

When installing to a location to which the current user has write access, the script does NOT use `sudo`. 

However, we cannot guarantee that the user's shell is configured to have a custom install location in their `PATH` and we cannot safely make assumptions about how to update the user's `PATH` in a persistent manner.

> I don't know what the script does, and giving root credentials to an unknown bash script is not a good practice

Concerns about running arbitrary script code are entirely valid. In that case, it's recommended that the user validate the script before running or install manually by downloading the binary file from our GitHub release, placing that file in a location on the local machine, and ensuring that the location is present in their shell's `PATH`. I'll update our install docs to describe this. https://github.com/Azure/azure-dev/blob/main/cli/installer/README.md

> Depending of the Linux distrib used, /usr/local/bin may not exist, as reported here: https://github.com/Azure/azure-dev/issues/1670

The broader point of this location not existing is something that we're actively investigating. It was believed to be a reasonable assumption that `/usr/local/bin` exists and is in `PATH` on both Linux and MacOS. We might make changes to the install script as a result. `/usr/bin` is another reasonable contender for an install location on Linux and possibly on MacOS. 

To the specific point: The issue linked is for MacOS which is not a flavor of Linux. I'm not aware of a Linux distribution in common use that does not have the `/usr/local/bin` directory present and in `PATH` by default.

> This doesn't give me any way to easily clean up what was installed

Our [uninstall](https://github.com/Azure/azure-dev#uninstall-azure-developer-cli) script can be used to uninstall `azd` if it's installed in the default location.

**Comment by sinedied** [comment]
Hi Daniel, thanks for the detailed response!
Allowing to use a custom install location is a good workaround, as well as `brew` distribution. 👍 

I would love to see these details added to the README though as it's not really obvious these options are available, and others could easily miss it (like me).

**Comment by danieljurek** [comment]
@anfibiacreativa - I opened https://github.com/Azure/azure-dev/issues/1691 to track the issues you were seeing. I think the error you're seeing should be investigated independently of this issue.
