### ISSUE TITLE
`azd pipeline config` action logs fail with todo-nodejs-mongo-aks

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1686]
**Describe the issue:**
When performing pipeline test,  `Azure Dev Provision ` fail in action logs.
The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/223629218-a815068f-75a1-4d6c-8f6f-0d9276226504.png)

**Repro steps:**
1. Run command `azd login`.
2. Run command ` bash ./test-templates.sh -t todo-nodejs-mongo-aks -b pr/1630`.
3. Run command ` azd pipeline config`.

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, WSL.
Template: todo-nodejs-mongo-aks.
Azd version: 0.6.0-beta.3-pr.2605958  (commit https://github.com/Azure/azure-dev/commit/be4d3dffd5ca305657aa0c6d9c64911c44caef63)

**Expected behavior:**
`azd pipeline config` action logs can success.

@rajeshkamal5050 for notification.

**Comment by wbreza** [comment]
@v-jiaodi What role is the service principal used in this example?

**Comment by vhvb1989** [comment]
@wbreza , for what I see, this error is happening when the pipeline runs within a new repo.
In that case, the `service principal` is the one created by `azd` which is Contributor for all the subscription.

I would expect this to be reproducible by running `azd pipeline config` -> Create a new private GitHub repo -> Start the pipeline...  then the issue would be there.

The other possibility is that, since we are running `bash ./test-templates.sh -t todo-nodejs-mongo-aks -b pr/1630.` first, it means that `provisioning` and `deploy` is happening on the local machine. So, when this happen, the Azure resources assign the owner role to the user who ran the test.
Then, when `azd pipeline config` runs and creates a new service principal, even though it has Contributor role, it has no access to some of the resources. 

I think I have seen this as well with Key Vault...  because when the key vault is created, we set the owner to be the only one with read/write access to the secrets.  We also set read access for the api-service, so when the app runs on Azure, it can read the secrets..  But we don't assign read access to any `service principal` created later...

**Comment by wbreza** [comment]
#1630 fixes the next issue  you would encounter where `kubectl` is not available.

**Comment by v-jiaodi** [comment]
Retest with https://github.com/Azure/azure-dev/pull/1630, after running `azd pipeline config --principal-role owner`, this issue cannot be reproduced, but a new error has occurred in `Azure Dev Deploy`  in action logs. The error message as follows:

![image](https://user-images.githubusercontent.com/80496810/223972117-514fc2bf-06f8-40ac-a063-4a04f52776c9.png)
