### ISSUE TITLE
[Issue] azd infra create --output json --no-prompt prints wrong output format

### ISSUE THREAD

**Issue by abpiskunov** [Azure/azure-dev#1689]
When we call azd from VS we established a contract earlier where we understand json output and forward messages to the output panel of the VisualStudio as they are. 

However recently messages texts instead of being just texts got some additional info appended and have some extra symbols added. Now when we print them in VS output it looks weird. Where this change came from? Could it be reverted or adjusted? Are there unit tests inplace to protect from breaking changes like this?

Current Azure Developer CLI environment: aaaqq1q1q1q
Provisioning Azure Developer CLI environment resources ...
azd infra create --output json --cwd Z:\git\ms\AzdNewSample --no-prompt
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time
Show spinner with title: Creating a deployment plan
Stop spinner with title: 
Show spinner with title: Creating/Updating resources
You can view detailed progress in the Azure Portal:,https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F07268dd7-4c50-434b-b1ff-67b8164edb41%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Faaaqq1q1q1q
Show spinner with title: Creating/Updating resources
(âœ“) Done: Creating Resource group: rg-aaaqq1q1q1q
Show spinner with title: Creating/Updating resources (Key vault, Log Analytics workspace)
Show spinner with title: Creating/Updating resources (Key vault, Log Analytics workspace)
(âœ“) Done: Creating Key vault: kv-gc3qrtrrx4mzu
(âœ“) Done: Creating Log Analytics workspace: log-gc3qrtrrx4mzu
Show spinner with title: Creating/Updating resources
(âœ“) Done: Creating Application Insights: appi-gc3qrtrrx4mzu
Show spinner with title: Creating/Updating resources
(âœ“) Done: Creating Portal dashboard: dash-gc3qrtrrx4mzu
(âœ“) Done: Creating App Service plan: plan-gc3qrtrrx4mzu
Show spinner with title: Creating/Updating resources (Azure Cosmos DB)
Show spinner with title: Creating/Updating resources (Azure Cosmos DB)
Show spinner with title: Creating/Updating resources (Azure Cosmos DB)
Show spinner with title: Creating/Updating resources (Azure Cosmos DB)
(âœ“) Done: Creating App Service: app-web-gc3qrtrrx4mzu
Show spinner with title: Creating/Updating resources (Azure Cosmos DB)
Show spinner with title: Creating/Updating resources (Azure Cosmos DB)

**Comment by vhvb1989** [comment]
is `(âœ“)` the symbol you are referring to?

**Comment by abpiskunov** [comment]
yes and this prefixes : "Show spinner with title: " it dd not show up before , just the actual messages for user: "Creating/Updating resources (Azure Cosmos DB)"

**Comment by vhvb1989** [comment]
> Are there unit tests inplace to protect from breaking changes like this?

We don't have a solid spec about json output.  I think it is currently only used from VS.  I can follow up with @ellismg about creating some spec and a CI gate to prevent breaking it.

**Comment by vhvb1989** [comment]
Creating PR to have the output as:

```
Current Azure Developer CLI environment: aaaqq1q1q1q
Provisioning Azure Developer CLI environment resources ...
azd infra create --output json --cwd Z:\git\ms\AzdNewSample --no-prompt
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time
You can view detailed progress in the Azure Portal:,https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F07268dd7-4c50-434b-b1ff-67b8164edb41%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Faaaqq1q1q1q
Done: Creating Resource group: rg-aaaqq1q1q1q
Done: Creating Key vault: kv-gc3qrtrrx4mzu
Done: Creating Log Analytics workspace: log-gc3qrtrrx4mzu
Done: Creating Application Insights: appi-gc3qrtrrx4mzu
Done: Creating Portal dashboard: dash-gc3qrtrrx4mzu
Done: Creating App Service plan: plan-gc3qrtrrx4mzu
Done: Creating App Service: app-web-gc3qrtrrx4mzu
SUCCESS: Your project has been provisioned!
```

Would that work for you @abpiskunov ?  Or are you hoping to `do not` show the `Done: Creating xxxx: xxxx` description at all?
There's also one last output to indicate SUCCESS.

**Comment by rajeshkamal5050** [comment]
Re-opening and adding the discussion from chat here,

[10:23 AM] Anton Piskunov
I just tried it and its changed now. However i feel i was too quick responding yesterday in that PR, I had in impression it first prints "Started creating a resource" and then "Done: creating a resource". However it only prints "Done: creating a resource" after it was created. and then we wait for next message. It does not say what is it doing now. Is that expected for you?

[11:35 AM] Victor Vazquez
Yes.
We do show current status in the console and we update the messages and order as the status is changing.
This is not equivalent in json because each change would result in a new message instead of just an update to previous message.
If you don't need tracking and showing each resource as it is created, we can remove that from Json output and it would be just the start message with the link to the azure portal, a note about it will take some time and a final message with the results 

[12:10 PM] Anton Piskunov
We do care about progress in the output since otherwise it would stay silent for minutes and it is not a good experience. I believe we need help from PMs to define the "experience" how user would interact with all 3 tools. Write it down in short spec ( i believe all 3 tools should have identical interaction ini this particular example). Then devs should implement it and agree how to keep it in sync, to avoid a random PR change the experience here and there. cli output vs json is implementation detail and users would not care why some things are looking/behaving differently.

@savannahostrowski @AngelosP please take a look and let us know if this experience https://github.com/Azure/azure-dev/issues/1689#issuecomment-1494906639 is okay for 0.8 and we can iterate on it post GA?

**Comment by vhvb1989** [comment]
removing `blocker`.  We can improve the output and experience of what customers will see as part of next iterations.
For 0.8, we will be fixing the weird symbols from the output

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @ellismg don't think we are going to change the output formats between now and GA. Moving this to backlog.

**Comment by vhvb1989** [comment]
Closing as the original issue was resolved and if there is a new issue with VS parsing azd output, we should create a new issue
