### ISSUE TITLE
[azd provision] overrides all previous `tags` from resources on each `provision`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1782]
repro:
- azd provision
- Update `resource group` -> add more tags to the resource group.
- azd provision

The tags are removed and only `azd-env-name` is added as tag

@ellismg , is it possible to fix this within the bicep files?
I am guessing that we will need to remove the `tags` from bicep and make `azd provision` to take care of appending the required tags only when missing

**Comment by weikanglim** [comment]
@vhvb1989 You can update `bicep` to do an append-operation, but generally `bicep` should be a declarative state of the infrastructure. Users should not modify Portal resources ad-hoc, unless the intention to apply a change temporarily for ad-hoc testing.

**Comment by jongio** [comment]
Last I checked, bicep doesn't have native union ops. We would need to query the resource group to get the current tags, then append with the new tags.

**Comment by jongio** [comment]
I have found that approach to be buggy and inconsistent and I moved away from it - there's a chance I was doing something wrong, but I would want to test to make sure that we don't have intermittent failures.

**Comment by weikanglim** [comment]
@takyyon Depending on what you're trying to do, that may the correct solution. If you're looking for a strict append, using `bicep` to query + merge maybe more desirable than using the environment file.

This example may illustrate:

On a new machine, and let's say that the bicep resource has `tags: key1=value1`

1. Run `azd provision` once.
2. The resource is tagged with `key1=value1`. The `.env` file now has `AZURE_TAGS:key1=value` defined.
3. Modify bicep resource to have tags `key2=value2`. Run `azd provision` again. Since `AZURE_TAGS` was present and used, the resource now has `key1=value1,key2=value2`

Which works well.

However, if you happen to run `azd provision` on a fresh machine, or on a CI machine, `AZURE_TAGS` would not be primed with a value, and would end up updating the resource with tag set **only** to `key2=value2`

It is also important to note that if you made tag updates in Portal, those updates will not be kept. This may or may not be desirable for your needs.

**Comment by rajeshkamal5050** [comment]
Not a must-fix for GA. Since this is a requirement from BYO-infrastructure which is handled in Gallium.

Moving it to Gallium.

@savannahostrowski @ellismg

**Comment by ellismg** [comment]
The work to do resource group scoped deployments has addressed the root of the issue here, especially as it relates to the case where the resource group is created outside of `azd`.  In these "bring your own resource group" cases, we don't touch the tags at all.

If your template is deployed at subscription scope and you use it to create a resource group (as our ToDo templates do) and you go mucking about with the tags of that resource group manually, future `azd provision` calls will revert the tag back to what your template describes.  The ARM Control plane is doing this work as part of pushing the cloud towards the desired state described by the template.  You'll see the same behavior with Terraform.
