### ISSUE TITLE
azd pipeline config  `Log in with Azure` fail in action logs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1869]
**Describe the issue:**
Failing to login with azure in action logs, when run `azd pipeline config`.

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/229764423-57e50247-1ab6-4919-bea6-fe68bf59f4ed.png)

**Repro steps:**
1. Run command `azd login`.
2. Run command ` bash ./test-templates.sh -t xxx -b staging`
3. Run command `azd pipeline config`

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, WSL.
Template: all templates.
Azd version: 0.7.0-beta.2-pr.2672227  (commit https://github.com/Azure/azure-dev/commit/dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
`azd pipeline config` can pass.

@rajeshkamal5050 for notification.

**Comment by vhvb1989** [comment]
this issue is happening because the `azd` running within the pipeline is the last released 0.7.0 and it does not know about `azd auth login` .
version 0.7.0 only knows about `azd login`.

Before releasing version 0.8.0, before running the pipeline, we need to set the azd version to be used to be the `daily` build instead of the `latest`
This is done from the `.github/azure-dev.yml` on the line:
`image: mcr.microsoft.com/azure-dev-cli-apps:latest`  to `image: mcr.microsoft.com/azure-dev-cli-apps:daily`
