### ISSUE TITLE
As a user, I can easily see existing deployed endpoints and environments relevant to my application 

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1887]
I'm thinking that'd be nice to be able to run something like a human-readable `azd show` and see something similar to what we see in the VS Code application tree view (app name, env, services + endpoints).

In VS Code:
![image](https://user-images.githubusercontent.com/8949415/235265800-ddfbd831-2a68-4f3e-bedd-04f26e085a8a.png)

Something like this but maybe a table, if it makes sense:
```
Application name (e.g. name in azure.yaml: todo-python-mongo-aca)
	Services
		Service 1 - <clickable endpoint, if applicable>
		Service 2 - <clickable endpoint, if applicable>
		...
	Environment
		[Default] Env 1
		Env 2
```

It'd also be cool to be able to see this on a subscription level (e.g. if you passed in a --subscription, flag), you could see a table of all the running apps/endpoints.

**Comment by savannahostrowski** [comment]
@savannahostrowski to spec

**Comment by savannahostrowski** [comment]
Factor https://github.com/Azure/azure-dev/issues/1165 into the design

**Comment by Austinauth** [comment]
# Design Update

After a round of sketching and feedback we have agreed on the following design for `azd show`.

![image](https://github.com/Azure/azure-dev/assets/6994218/944d7b84-7a75-441a-b7c1-75a90d4d2c12)

## Design notes
- We understand the long hyperlinks are not super visually appealing, but they are more accessible than using custom hyperlink text. This also better accommodates users who rely on copy/paste to visit URLs.
- **Future:** We should investigate a general tag or flag for accessibility so that we might utilize custom URLs or other patterns that can be an accessibility issue (truncation). This is something we should have a strategy for across _all_ commands before implementing.
- The team collectively decided to refrain from implementing an `azd show -subscription` until we have a better understanding of how it will work.

## Questions
cc: @gkulin @savannahostrowski 

- Is there any additional helper text we want to add at the end of this command's output?
- What are the edge cases I still need to provide designs for?
  - No app in current directory?
  - App detected but not deployed?
