### ISSUE TITLE
Azure Container Apps CORS issue

### ISSUE THREAD

**Issue by giannicaringi** [Azure/azure-dev#1893]
I have a big problem with my web app. Starting with some info... the backend is in ASP.NET Core 6, and the frontend is in React. I deploy this site using Azure Container Apps inside the same Resource Group end in the same Container Environment.

All works fine until I decided to change backend visibility from External to Internal. From this moment, when the frontend calls backend I have CORS error and the backend is never called.

Inside the Program.cs of the application is managed yet the CORS policy that accepting ALL. But it still don't work.

NOTE: I can't expose my backend public.

**Comment by rajeshkamal5050** [comment]
@giannicaringi did you try with the latest Azd bits and templates. There was a recent fix we made #1899 @hemarina @vhvb1989

**Comment by vhvb1989** [comment]
@giannicaringi , is your template public?  If not, can you share:
- How you are setting cors for .cs ?
- How you are hiding the endpoint from the server?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @hemarina can we close this? this should be handled as part of the fixes you made recently?

**Comment by vhvb1989** [comment]
@rajeshkamal5050 , we don't have any template for .Net in the backend hosted in `aca` 

For .Net, we host on web-apps only (including `funct`).

Also, our .Net templates don't have CORS implemented at application level. Since we use `web-apps`, we rely on it for setting and controlling CORS.

When it comes to Azure Container Apps, there's is not CORS supported from the service (not that I am aware of). What we do is to use CORS at application level in that case, setting the frontend url as env-var for the backend container. Then the backend application gets the url and make it an allowed url.

But for what @giannicaringi is saying, the backend application is not setting CORS and it should be allowing all requests.

This is indeed not an azd bug, but it would be interesting to see if @giannicaringi has found the issue and a solution here for what configuration he needs

**Comment by vhvb1989** [comment]
Well, `cors` is now supported by `aca`
https://learn.microsoft.com/en-us/azure/container-apps/cors?pivots=azure-portal&tabs=arm

It is on preview.

@giannicaringi check if this setting is enabled on your backend container and if so, add the frontend url to the allowed origins
