### ISSUE TITLE
[Issue] Azure.yaml - terraform is not a valid value 

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1925]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)

**Describe the bug**

The JSON schema backing the `azure.yaml` (<https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json>)was changed with version 0.8.0 of `azd` restricting the allowed values for the `infra.provider` to `bicep`.

Although the provisoning via Terraform became a alpha feature that needs to be explicitly enabled, the JSON schema should either allow this value or a new version of the JSON schema should be created that is shipped with the templates. 

**To Reproduce**

- Execute `azd init -t Azure-Samples/todo-nodejs-mongo-terraform`
- Open the cloned project in VSCode
- Open the `azure.ymal` file

=> you will find a red curly line underlining the provider value `terraform` 

**Expected behavior**

As mentioned above:

- Either the Terraform provider is a valid value again for the enum in the infra section of the `azure.yaml`
- A new version of the JSON schema is released that is not containing Terraform. However the original version should still contain the Terraform as a valid value and should then be referenced by the "old" Terraform templates

**Environment**

n/a

**Additional context**

n/a

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @ellismg 

Since being in active development and is prone to change in future releases - https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/feature-versioning

Similar to springapps which isn't also called out as part of azure.yaml. We will be following the same for terraform too? Also, we don't have a alpha/dev yaml published today. There could be implications in other areas of the system w.r.t to a new alpha/dev yaml?

Is this a GA blocker? Can we handle post GA?

**Comment by ellismg** [comment]
I think the best thing for us to do now is to create another copy of this schema which tracks all the features supported when all the alpha flags are on.  We can use this as a place to document the alpha features without worrying about confusing the existing schema consumers.  I opened #2251 to do this.

Folks that want intellisense for the alpha features can update the URL to point at the alpha schema after we check it in.
