### ISSUE TITLE
Why does `azd init` only support `--subscription` and not `-s`?

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2050]
All the other flags for init support the shorthand flag (e.g. `-t`, `-e`) and (e.g. `--template`, `--environment`)

For `--subscription`, we don't seem to support `-s`. Is this intentional? At a glance, this seems inconsistent.
![image](https://user-images.githubusercontent.com/8949415/235255862-b7be1db6-3a10-49d4-a046-04ed1a583d45.png)

**Comment by ellismg** [comment]
It was not intentional.  We added this flag (as well as location) for use by VS when they ran `init` (so they could prevent prompting from AZD, back when init asked for these values) and so just having `--subscription` was fine because that is what VS was coded to use.  We will add this back for consistency.

**Comment by rajeshkamal5050** [comment]
@v-xuto can you create a PR for the above `-s` flag?

**Comment by v-xuto** [comment]
> @v-xuto can you create a PR for the above `-s` flag?

Sure. We are currently working on it.

**Comment by v-xuto** [comment]
@rajeshkamal5050 The PR for this issue is ready, please review.
- PR link: https://github.com/Azure/azure-dev/pull/2708
