### ISSUE TITLE
Azure Dev Provision failed in pipeline logs when "azd pipeline config"

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2143]
**Describe the issue:**
Github pipeline test failed when run `azd pipeline config --provider github` in Devcontainer and Windows.

The error message as follows:
![image](https://user-images.githubusercontent.com/112381413/237053550-089e1227-ac7c-4a52-81c7-041c64f77afe.png)

**Repro steps:**
1. Run `azd auth login`
2. Run `azd up`
3. Run `azd pipeline config --provider github`

**Environment:**
OS: DevContainer, Windows desktop.
Template: https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application
Azd version: 0.8.0-beta.3-daily.2760917 (commit https://github.com/Azure/azure-dev/commit/2201b16963dc43ae045c52374c0dd395152cb309)

**Expected behavior:**
Run command `azd pipeline config` success.

@rajeshkamal5050 for notification.

**Comment by vhvb1989** [comment]
The template is broken after the changes to Github secrets to variables: https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/blob/main/.github/workflows/azure-dev.yml#L56

Pipeline is looking for a secret instead of a variables.

We should re-consider the strategy for the breaking change.  For example, pushing the `secret` for backwards compatibility and also the variable.  And display a deprecating message for the secrets.

**Comment by yiliuTo** [comment]
@vhvb1989 , is that to say I should change the github workflows from using secrets to using variables, just like what this pr did - https://github.com/Azure/azure-dev/pull/2126/files#diff-e7874a78880261b077352d35b9ef14030916897112090effe2c610a9eb0748ae

**Comment by rajeshkamal5050** [comment]
Yes @yiliuTo

**Comment by yiliuTo** [comment]
Hi @rajeshkamal5050 , this can be fixed by the solution you suggested and has been tested by Tong Xu according to the commit https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/4/commits/6a8ecbbdbe3594ff72d2132520f8a96542c32089.

**Comment by yiliuTo** [comment]
Closing this issue since it has been fixed by https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/4 and has been validated.
