### ISSUE TITLE
ARM 64 beta notification

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2183]
`azd` client -- Notify user during all commands that they're using a beta version of `azd` compiled for ARM64 scenarios. If they encounter errors, open an issue using this link: https://github.com/Azure/azure-dev/issues/new?assignees=&labels=&projects=&template=issue_report.md&title=%5BIssue%5D

engsys -- Add publishing of azd-darwin-arm64.zip to release job

**Comment by savannahostrowski** [comment]
To clarify, I just meant to notify them on initial install (similar to our telemetry notice)/ We don't need to notify them on all commands. That would a little heavy handed IMO

**Comment by rajeshkamal5050** [comment]
@savannahostrowski Since we aren't integrating mac arm64 bits with any install scripts and/or brew. Even the telemetry notice wouldn't be there. Hence, I believe @danieljurek was thinking to add to all commands. Which is too noisy.

Can we instead name the zip and the self contained binary itself as azd-darwin-arm64-beta.zip and azd-darwin-arm64-beta?
