### ISSUE TITLE
Running bicep fails in a completely blank ubuntu container

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2197]
Use this dockerfile: 

```Dockerfile
FROM ubuntu

# Add basic requirements
RUN apt update && apt install -y curl git

# Install Node (required for azd commands to work)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
    apt-get install -y nodejs

# Install azd 
RUN curl -fsSL https://aka.ms/install-azd.sh | bash

# Produces the bicep error
RUN mkdir azd-test \
    && cd azd-test \
    && azd init --template Azure-Samples/todo-nodejs-mongo \
    && azd provision

```

Error message: 

```
#0 2.026 Downloading Bicep
#0 4.821
#0 4.821 ERROR: creating provisioning manager: error creating infra provider: error creating provider for type 'bicep' : checking bicep version: signal: aborted
```

Running the downloaded bicep gets you: 

```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
...
```

And this can be solved by setting the environment variable 

```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

It might make sense for us to do this directly in our code if we envision running in this kind of environment.

**Comment by leanderkunstmann** [comment]
@savannahostrowski I have a similar problem, therefore it is not that uncommon. I wanted to build a custom docker container image for using azd (as we really like using it instead of az and terraform combined with other stuff) for deployment in gitlab-ci (as we do not use github). As the provided container image by MS is really big and has a lot of overhead installed to fit more use cases, I created a custom one, which worked fine until this error popped up. In my opinion it should work with using terraform as infrastructure provider, but bicep is preferred in my case.

**Comment by savannahostrowski** [comment]
Yeah that makes sense. Thanks for providing more context here. I think I misunderstood the original issue filed.

This seems like a bug.

**Comment by rajeshkamal5050** [comment]
@danieljurek @ellismg if a Dotnet core/runtime install issue on Linux required for Bicep. 

Should we point here [Install .NET on Linux by using an install script or by extracting binaries](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#dependencies) or should this be custom handled in azd?

**Comment by ellismg** [comment]
To me the root cause of the issue here is that bicep doesn't work out of the box in the container image he built, because that container is missing libicu, which is something .NET Core Apps need, even when they are built standalone.

Running bicep directly fails, but with a good and actionable error message, however from the message that @danieljurek 
showed from `azd`, that message is lost, and so the user can not self solve, either by setting that environment variable, or installing a package to provide libicu (in this case, @danieljurek, you could add `apt-get install libicu70` which would install the globalization library that the .NET application needs).  We should try to fix that, so that when we fail folks have a shot at self solving.

Now, as to what we should do about this,  I think that in practice, it would probably be fine for us to set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 when running Bicep.  Reading over https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md it does not seem like it would bite us in our use of bicep.  It looks like bicep could opt into this behavior themselves if they wanted, at the app level, which could be nice.  I can't imagine that these changes would impact their tooling.

But, we will be swimming a bit upstream, if there are other paths that end up pulling in other .NET Core based tools (I don't think we have such a thing today, but it might happen in the future, maybe powershell?) and so it's probably worthwhile to just install `libicu` on the machine if you are going to be using bicep.

Note that because of how ICU versions, the name of the package you have to `apt-get install` changes across distributions, since the package name includes the version of the data.  I had to use `apt search libicu` to find the name of the package.

**Comment by ellismg** [comment]
When we add our dev-container feature, we should consider installing this package as part of our setup.  We can use something like:

```sh
apt-cache search '^libicu[0-9]+$' | cut -d' ' -f1
```

To find the name of the package to install, which should make our setup script more portable (at least across debian based distros, which seems like how most of the other features end up working).

@leanderkunstmann you can also work around this issue by installing libicu in your container, if you had not figured that out.  It should not bloat the container too much.  Interested if you ended up doing that or just setting DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 yourself?

**Comment by rajeshkamal5050** [comment]
> When we add our dev-container feature, we should consider installing this package as part of our setup. We can use something like:

@hemarina for handling the above as part of devcontainer feature being worked on for current iteration.

@leanderkunstmann please try the above workaround and let us know.

**Comment by ellismg** [comment]
Due to how bicep was exiting we were not including this text in the output of the error.  #2438 fixes that, and now the error you would see would look like this:

<img width="1423" alt="image" src="https://github.com/Azure/azure-dev/assets/9602953/8a13e3be-8ab2-46af-8b12-2eead85bf666">

Much nicer, and easier to self solve.

**Comment by leanderkunstmann** [comment]
> > When we add our dev-container feature, we should consider installing this package as part of our setup. We can use something like:
> 
> @hemarina for handling the above as part of devcontainer feature being worked on for current iteration.
> 
> @leanderkunstmann please try the above workaround and let us know.

adding 
`RUN apt-get install libicu70`
to my dockerfile fixed the issue, now I am able to deploy with azd inside the container.

Thank you for the workaround, helps me a lot.
