### ISSUE TITLE
`template list` is illegible in any size terminal

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2198]
![image](https://github.com/Azure/azure-dev/assets/8949415/0d21bfc1-6a30-4b53-a509-94f41b9125cb)

**Comment by rajeshkamal5050** [comment]
@weikanglim can we hide description from listing and the template show can have the desc details?

**Comment by Austinauth** [comment]
This definitely needs to be fixed. If we want to keep the descriptions their current length then the solution needs to be to fix the table cell wrap. 

Here's a quick example to illustrate:

<img width="1353" alt="image" src="https://github.com/Azure/azure-dev/assets/6994218/4594dbba-f71d-4106-958f-3f761520701e">

I'll mock something up for azd asap.

**Comment by savannahostrowski** [comment]
Do we have any snapshot tests that needed to be updated to catch stuff like this?

**Comment by weikanglim** [comment]
@savannahostrowski We have snapshots for all our usage text, not for command output. Personally, I think the bug here is that we have a "table format" that hasn't been put to the test. The text wrapping is definitely not how table formats should work.

 As @rajeshkamal5050 suggests, can we remove Description for now? Here's how it looks like:
![image](https://github.com/Azure/azure-dev/assets/2322434/c5be38e5-8c19-4102-b9d3-d99e1faf1b2b)

**Comment by savannahostrowski** [comment]
That seems reasonable for now - @Austinauth any concerns?

**Comment by Austinauth** [comment]
Works for me 👍
