### ISSUE TITLE
Unable to run deploy without provision in CI/CD (via GHA)

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2208]
I was experimenting with adding a conditional filter to only run `azd provision` in CI/CD when files in `infra/` have been updated, using https://github.com/dorny/paths-filter. 

However, I ran into an error on the deploy step where azd is telling me that provision is required before deploy. This application has been both provisioned locally and in previous pipeline runs before adding the filter, and is currently alive and running on Azure. Additionally, all the right repo variables have been set here (e.g. AZURE_CLIENT_ID, AZURE_ENV_NAME, AZURE_LOCATION, AZURE_SUBSCRIPTION_ID, AZURE_TENANT_ID) so this seems like a bug?

https://github.com/savannahostrowski/build-demo-session/actions/runs/4974176748/jobs/8900456465

**Comment by weikanglim** [comment]
@ellismg May need your guidance here. It looks like we're performing `env.Values[AZURE_SUBSCRIPTION_ID]` which only works if the variable is set explicitly in `.env`, but wouldn't work if the `AZURE_SUBSCRIPTION_ID` is set on the OS. 

I'm not sure about the consistency of what rules should apply where, but the quickest fix is to definitely change to the read to respect `os.env`.

**Comment by ellismg** [comment]
I spent some time thinking and playing around with this.

To, @weikanglim's line of thinking, I went refactored the Environment class slightly such that `.Values` was not exposed, which forced me to examine every read of it in the codebase and think about "do I want to fall back to the operating system here or not".  The outcome of that exercise is in #2238 and there I biased towards "Yes, we should fall back to the operating system environment, because doing so makes it easier to solve cases like the above where the .env file may not be persisted but you are willing and able to put all the necessary information in the operating system environment".

With that change, I was able to take the private container and use it in scenario like @savannahostrowski describes above and the deploy worked (as we would expect and @weikanglim figured it would).

I realized, however, that this would not always be the case.  For example, if you are using container apps, one of the pieces of state information that we need is "the container registry we need to push the container image to".  The way we do that today is look for a well known environment variable with the registry name and expect it to be there because it's an output of the main.bicep we deploy.

In @savannahostrowski's case here, we don't run `provision` so the output doesn't end up in the .env file.  Since it won't be set in the CI environment (since it realistically can't be) the deploy of the container app would fail and ask you to set this value.

This means that even in the "no-op" case, we may need outputs from `provision` to be around.

I tried taking the bits we have today and replace the `provision` step in the pipeline with one that runs `azd env refresh --no-prompt`.  Doing that works (given that I have already provisioned the infrastructure once) and allows `azd deploy --no-prompt` to work as well.  This would also work even if you were using container apps, where as simply using the bits from #2238 would not.

We could consider trying to update the error message to point folks this way.  For example, today we do:

ERROR: infrastructure has not been provisioned. Please run `azd provision`

We might try something like:

ERROR: infrastructure has not been provisioned. Please run `azd provision`.  If your infrastructure was previously provisioned on a different machine, consider running `azd env refresh` to refresh your local state.

@savannahostrowski I think if you update your pipeline so that in the conditional case where there are no changes you just run `azd env refresh --no-prompt` as you would have run `azd provision --no-prompt` things will work for you.

**Comment by savannahostrowski** [comment]
Ah yeah, that makes sense. Your suggestion did work https://github.com/savannahostrowski/build-demo-session/actions/runs/5007856842!

I think it'd be good to print " If your infrastructure was previously provisioned on a different machine, consider running azd env refresh to refresh your local state." out as you suggest! Thanks for the thorough investigation/explanation.

Did you want to squeeze that in before release tomorrow and we can close this out?
