### ISSUE TITLE
VS Code test  failed for todo-java-postgresql-terraform

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2268]
**Describe the issue:**
Hit F1 Run Task `Start API and Web`, `Debug API Failed`.

**The error message as follows:**
![image](https://github.com/Azure/azure-dev/assets/112381413/620c463f-cc15-41f9-ad02-71a3d01a4b48)

**Repro steps:**

1. Run `azd auth login`
2. Run `azd init -t todo-java-postgresql-terraform -b staging`
3. Run `azd up`
4. Hit F1 Run Task `start API and Web`

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, DevContainer in VS Code.
Template: todo-java-postgresql-terraform
Branch: staging
Azd version: 0.9.0-beta.2-daily.2786873 (commit de89effa931a89e8125e520e5bc3ff473f014fb5)

**Expected behavior:**
Run task `start API and Web` success.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@blow-hey does this still repro with the latest bits and templates?

@yiliuTo can you triage this with @blow-hey

**Comment by yiliuTo** [comment]
@rajeshkamal5050  sure

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue can be reproduced in the following cases：

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.1.0-beta.1-daily.2845223 (commit https://github.com/Azure/azure-dev/commit/9e11674b30a1b0c456fbd8a042d6f5af77ec6188)

**Comment by yiliuTo** [comment]
Hi @v-jiaodi and @rajeshkamal5050 , I am using azd version 1.0.2-daily.2861384 (commit bb510e6f0bd9083210ac640f43b1bcff622d07b4) retrying to reproduce this error, however, before running to the provision stage, I encountered error in the provision stage:
![image](https://github.com/Azure/azure-dev/assets/63028776/b66e65b4-c97b-4284-95f2-f01a16d943d8)

Could you check which hosting do you use? App service or Spring Apps?

**Comment by vhvb1989** [comment]
> Hi @v-jiaodi and @rajeshkamal5050 , I am using azd version 1.0.2-daily.2861384 (commit [bb510e6](https://github.com/Azure/azure-dev/commit/bb510e6f0bd9083210ac640f43b1bcff622d07b4)) retrying to reproduce this error, however, before running to the deploy stage, I encountered error in the provision stage: ![image](https://user-images.githubusercontent.com/63028776/248682058-b66e65b4-c97b-4284-95f2-f01a16d943d8.png)
> 
> Could you check which hosting do you use? App service or Spring Apps?

@yiliuTo , make sure that 'az cli' is set to to use the account/subscription that you are using with azd.
Run 'az account show' and see if the subscription you see there is the one used with azd.
If not the same, run 'az account set --subscription xxxxx' .
Then continue the test.

**Comment by yiliuTo** [comment]
@vhvb1989 thanks your solution works. And after reproducing this issue, I found the cause should be that this application lacks some environment variables for the application configuration:
https://github.com/Azure-Samples/todo-java-postgresql-terraform/blob/3ccadf24336d8a207a5eacf95c8513667559b447/src/api/src/main/resources/application.properties#L8-L9

When running in azure app services, those env vars can be configured through [terraform](https://github.com/Azure-Samples/todo-java-postgresql-terraform/blob/main/infra/main.tf#L108-L109), however, when debugging with vscode, those vars are not configured:
https://github.com/Azure-Samples/todo-java-postgresql-terraform/blob/3ccadf24336d8a207a5eacf95c8513667559b447/.vscode/tasks.json#L16-L18.

And since those vars involve the resource information generated after `azd provision`, thus I am wondering are there any solutions to configure vscode environment vars with AZD environment vars? @vhvb1989 do you have any suggestions on this?

**Comment by vhvb1989** [comment]
@yiliuTo , the tasks.json uses the dotenv type to pull all variables from azd-env when launching services.
What you are missing is to make terraform to output the env-vars you need here: https://github.com/Azure-Samples/todo-java-postgresql-terraform/blob/3ccadf24336d8a207a5eacf95c8513667559b447/infra/output.tf#L1

There is already a value: `AZURE_POSTGRESQL_ENDPOINT` as output. After `azd provision`, this env var is set into azd-environment and it set when launching the api-service locally.  However, the api is looking for `AZURE_POSTGRESQL_URL` . So, you should consider using `AZURE_POSTGRESQL_ENDPOINT` for the api-config (unless the endpoint is different than the URL).

Since you are using `Passwordless` configuration (assigning access-roles to the webapp to access https://github.com/Azure-Samples/todo-java-postgresql-terraform/blob/3ccadf24336d8a207a5eacf95c8513667559b447/infra/main.tf#L123) , I think you will also need to create `passwordless` configuration for the current local-user (maybe that's already happening... )

So, try setting `AZURE_POSTGRESQL_USERNAME` and `AZURE_POSTGRESQL_URL` as output variables here: https://github.com/Azure-Samples/todo-java-postgresql-terraform/blob/3ccadf24336d8a207a5eacf95c8513667559b447/infra/output.tf#L1.  That should do the trick.

Note: If the Username and/or url are somehow sensitive info, consider creating a Key Vault and setting those values there. Then make the api-code to connect to KeyVault and pull the values from there.  This is what we do for the java template we have on Azure-Samples here: https://github.com/Azure-Samples/todo-java-mongo/blob/main/src/api/src/main/resources/application.properties#L8   .  The Spring app uses Key Vault as application-config, making all secrets available for the app as env-vars

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue can be reproduced in the following cases：

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.0.3-beta.1-daily.2905893 (commit https://github.com/Azure/azure-dev/commit/a7126c9e3b8573d3874c47adf0caad927a551d76)

**Comment by fangjian0423** [comment]
> I think you will also need to create passwordless configuration for the current local-user (maybe that's already happening..

hi @vhvb1989. Now the passwordless configurations is setting for Azure Service(via Managed Identity), not for the current local-user.

Adding passwordless configurations for local-user could resolve the issue. As we know, the template could be used in different scenarios:

- In the local env, local-user means the current login user
- In Github action, local-user means the AAD service principal

The logic in terraform local-exec should cover both scenarios (Maybe there are some other scenarios). It's a little complex for developers and also not easy to implement.

Thus, to make the template be simple, I will remove passwordless feature and use KeyVault to replace it.

**Comment by weikanglim** [comment]
Removing passwordless may be a better option for now. Passwordless postgresql implementation requires additional developer education and app coding to request the scoped token and pass it along as `DBPASSWORD` when establishing a database connection.

The only downside is non-trivial zero-downtime production secret rotations, but that hasn't been a primary focus of our current templates.
