### ISSUE TITLE
Support Azure China Region?

### ISSUE THREAD

**Issue by chaonengs** [Azure/azure-dev#2280]
Can I set azd region to China Cloud as az cli? cannot find introduction

**Comment by ellismg** [comment]
Sorry, we don't yet support clouds other than the Azure public cloud.

@savannahostrowski - Something for us to consider.  I am hopeful that the work would be small, since I think the major changes for supporting other clouds is that the endpoints of services are different, and we should be able to leverage https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud for most of what we need.  But I'm not sure what the implications for auth are (maybe it just works, maybe we need to do some work to support logging into "multiple clouds" in the same way we had to do some work for multi-tenant user accounts and we had a tail of issues when we landed that feature.

**Comment by savannahostrowski** [comment]
Closing in favour of #973
