### ISSUE TITLE
azd env refresh alters numeric string value in .env file

### ISSUE THREAD

**Issue by JayDoubleu** [Azure/azure-dev#2307]
**Output from `azd version`**
azd version 1.0.0 (commit ed2244cb62e7940ec5aceb3b68ea49158272dd7e)

**Describe the bug**
azd env refresh alters numeric string value in .env file

**To Reproduce**

1. Define a variable in the .env file. For instance: `AZURE_SUFFIX="01"`
2. Run the command: `azd env refresh`

**Expected behaviour**
I expect the `AZURE_SUFFIX` value to remain as `"01"` after running the command.

**Actual behaviour**
However, after running the command, the value of `AZURE_SUFFIX` is changed to `1`, effectively removing the leading zero.

**Comment by ellismg** [comment]
Just checking, @JayDoubleu - In this case is `AZURE_SUFFIX` also an output in your main.bicep?  If so, what is its type?

**Comment by JayDoubleu** [comment]
I have just set it to `output AZURE_SUFFIX string = suffix` for testing and got the same results.
azd up/provision or refresh will change the value from `"01"` to `1`

**Comment by ellismg** [comment]
This is happening because of some policy that is applied by the package we are using to manage the .env file:

https://github.com/joho/godotenv/blob/193c9aba29da4c48e5496452b6954785e897bfb4/godotenv.go#L166-L172

When saving the file, if a value for a key is an integer, the package ends up wanting to write it as:

```
KEY=<value_without_quotes>
```

And as part of doing that, they end up Printf'ing the value with the %d format string, so they leading zero is dropped.

It also means that any numbers end up not being quoted, and you can see this behavior in `azd env get-values`

For example, I wrote this very small main.bicep:

```bicep
targetScope = 'subscription'

output NUMBER_WITH_LEADING_ZERO_AS_STRING string = '01'
output NUMBER_WITH_LEADING_ZERO_AS_NUMBER int = 01 
```

The deployment object returned by ARM does the right thing here (modulo the casing of the output names, but that's an existing issue that `azd` works around:

```json
    "outputs": {
      "numbeR_WITH_LEADING_ZERO_AS_NUMBER": {
        "type": "Int",
        "value": 1
      },
      "numbeR_WITH_LEADING_ZERO_AS_STRING": {
        "type": "String",
        "value": "01"
      }
    },
```

But because of the above coercion to an int during save, we end up storing just 1 in the environment for both values (unquoted).  Here's what `azd env get-values` shows:

```
AZURE_ENV_NAME="matell-azure-dev-2307"
AZURE_LOCATION="eastus2"
AZURE_SUBSCRIPTION_ID="<redacted>"
NUMBER_WITH_LEADING_ZERO_AS_NUMBER=1
NUMBER_WITH_LEADING_ZERO_AS_STRING=1
```

I think is reasonable to emit numbers without quotes in the `.env` file, but I only think we should do it when it is non destructive.  But I could also see the argument that since the output of the bicep is typed as a string it should be written to the .env with quotes, even if the value happens to be numeric.

It does not look like the behavior here in `godotenv` is configurable, so we'll have to go our own way to support fixing this.

@JayDoubleu as a workaround, you could add a fixed prefix or suffix to the string output so that the value is no longer a valid number, and then strip that prefix or suffix down the line.

I'll work on fixing this for the case described above, but I do think we should think about if this bicep:

```bicep
targetScope = 'subscription'

output NUMBER_AS_STRING string = '1'
output NUMBER_AS_NUMBER int = 1
```

Should end up having:

```
NUMBER_AS_STRING=1
NUMBER_AS_NUMBER=1
```

or

```
NUMBER_AS_STRING="1"
NUMBER_AS_NUMBER=1
```

Written to the .env file.
