### ISSUE TITLE
azd environment is not used while doing `azd deploy`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2389]
While deploying a js app, I am expecting that the .env from azd is added and included when `npm build` is called. But this is not happenening.
It works like this only when `azd deploy` is called from azd hook

**Comment by ellismg** [comment]
This is by design.  We made changes on the run up to GA to stop injecting values from the environment into sub processes, except for in the case of hooks.

We wanted to limit the number of commands that could observe these values and we think that the right place do to this observation is just in hooks.

**Comment by vhvb1989** [comment]
> We made changes on the run up to GA to stop injecting values from the environment into sub processes

that's unfortunate :(  .  This breaks the general concept of what azd-environment is. For example, if you run `azd set AZURE_ENVIRONMENT_NAME foo` and then you run `azd init`,  azd respects this value from the environment.

But it looks like we want to limit the scope of the azd-environment to only things running directly within `azd`, as the concept goes away as soon as azd invokes an external command...  and the only exceptions are hooks.

I will just need to create a new issue to ask hooks to avoid falling into infinite loops, so I can use a postdeploy hook to run `azd deploy` :)
