### ISSUE TITLE
[Issue] UnmatchedPrincipalType with deployment

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2427]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

Whatever version is in the CI image

**Describe the bug**

When I run `azd up` locally, it works. However, when I run CI/CD, I get an error:

https://github.com/pamelafox/chatgpt-quickstart/actions/runs/5283586918/jobs/9560505267

```
Deployment Error Details:
UnmatchedPrincipalType: The PrincipalId 'c2b5a29073434e378c518cec9fd[32](https://github.com/pamelafox/chatgpt-quickstart/actions/runs/5283586918/jobs/9560505267#step:6:33)a8d' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.
```

I'm fairly certain that we've discussed an issue with `azd pipeline config` and principals, but I can't find an issue filed with this verbiage, so I'm filing this. Feel free to merge/close as dupe.

**To Reproduce**

Check out that repo
Run azd up locally
Run azd pipeline config
See build fail

**Expected behavior**

I expected the CI build to succeed

**Environment**

CI server

**Comment by vhvb1989** [comment]
Hey @pamelafox 

There's is a role-assignation defined within the [infra-bicep file](https://github.com/pamelafox/chatgpt-quickstart/blob/main/infra/main.bicep#L112) which is expecting to assign the role `openAiRoleUser` to the user who is running azd-provision.

When running on CI/CD, there is not a user running azd, but a Service Principal, so this step fails.

My understanding is that role is making sure that you can run the backend locally, which will use your user-crendential for talking to openAI service.

The same role is [assigned here](https://github.com/pamelafox/chatgpt-quickstart/blob/main/infra/main.bicep#L123) for the webapp which holds the backend on Azure, to allow the app to use the OpenAI service.

During CI/CD, you don't need to create a role-assignment for the Service-Principal (unless you are expecting to ever run the backend using that Service Principal to authenticate to Azure).  

Here is some things you can try:
1. Update the bicep file to only assign the role to the user by setting an input parameter and set that input by default to `false` (similar strategy used for APIM).  Then, add a note in the Readme for users to set that env-var ON if they want to run the backend locally.  

2. Another approach is to only update bicep with the input parameter and create a mapping for it to an env-var that is only set on github-workflow and use that input as the condition to exclude that role-assignation. This won't require users to opt-in for the role-assignment. Instead, makes bicep to detect when it is running on CI/CD 

3. Last option is to use a ServicePrincipal both locally and on CI/CD.  You would create the SP and login azd with it locally.  Then you would update the role-assignment from `user` to `service principal`, and it will work both locally and on CI/CD.  But you will need to add this note into the Readme, to tell folks they need to use a ServicePrincipal instead of their account

**Comment by pamelafox** [comment]
Ah, yes, that makes so much sense, thank you for the thorough explanation. I've gone with option 2 since it requires no work from the user:
https://github.com/Azure-Samples/chatgpt-quickstart/compare/main...pamelafox:chatgpt-quickstart:main?expand=1
