### ISSUE TITLE
[Issue] Errors from gh auth command

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2451]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

**Describe the bug**

At various points, when I run git commands, I see this output:

```
/home/vscode/.azd/bin/gh auth git-credential get: /home/vscode/.azd/bin/gh: No such file or directory
/home/vscode/.azd/bin/gh auth git-credential store: /home/vscode/.azd/bin/gh: No such file or directory
```

For example, I just saw it while running pipeline config:

```
? Would you like to commit and push your local changes to start the configured CI pipeline? Yes
/home/vscode/.azd/bin/gh auth git-credential get: /home/vscode/.azd/bin/gh: No such file or directory
/home/vscode/.azd/bin/gh auth git-credential store: /home/vscode/.azd/bin/gh: No such file or directory
```

But I also see it when simply running `git push`.

I assume it comes from this .git/config:

[credential "https://github.com"]
	helper = 
	helper = !/home/vscode/.azd/bin/gh auth git-credential

I'm thinking I probably was in a Dev Container when that was created, and now I'm no longer in it.

**To Reproduce**

Probably: open a template in dev container, run azd pipeline config, open template locally, git push ?

**Expected behavior**

I don't expect to see errors.
I don't know that the errors are actually causing anything to break, fortunately!

**Environment**

Version: 1.79.0-insider (Universal)
Commit: b9a77b3c7b43f229a430b28070250d55e5d14858
Date: 2023-05-31T20:19:54.210Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by vhvb1989** [comment]
> I'm thinking I probably was in a Dev Container when that was created, and now I'm no longer in it.

This is unfortunate :( 
The main reason why we choose gitconfig at folder level was to avoid system-wide changes, but this case was clearly not considered...

I think we can try migrating to the same approach we have for AzureDevOps, using the git-config per command invocation instead of persisting within gitconfig.

thank you for reporting this @pamelafox .  

Removing that gitconfig should unblock you for now, while we fix this case

**Comment by vhvb1989** [comment]
I need some input from @ellismg and @savannahostrowski here, as removing the current git-credential helper would have side effects to someone working on `codespaces`. Here's why:

By setting the local git-config (in codespaces) within the azd-project, we are not only making sure that `azd pipeline config` will successfully push code to any selected repository; we are also allowing any follow up calls to `git push` to work, (again, regardless of the selected repository).

One of the motivations for this approach was the next use-case:
```
As a customer, I open some azd-template using codespaces.
Then I run `azd pipeline config` and ask azd to create a new private git-repository.
Creating the repository has no issues because azd uses the gh-cli and NOT the auth-token from the codespace.
After the private github repo is created, azd uses `git` to push the code; but before that, azd creates the git-local-config for making git to use the gh-cli as credential. 
If the git-local-config is not set, if I try to make some changes and then to run `git push`, I get an error about I am not authorized... which is totally confusing because azd was able to push code just fine.
Having the git-local-config ensures a continuous flow, where I don't need to understand why I am not authorized, or why azd can push code, but I can't. 
```

In case of Azure DevOps, git is not affected by the codespaces credential, because the host is different. Hence, git will prompt for password all the times.

I consider that is worth it to keep the current strategy. The codespaces end-2-end flows with azd are solid.

One alternative is to apply the git-credential strategy only when azd is running on codespaces.
The side impact would be reduced to only azd-users on Win/Lin/mac who are not already using `git+.ssh keys` and/or a credential manager to keep their https token-credentials. 
This is a limited audience, IMHO, b/c installing git-for-windows installs a windows-credential-manager by default (which even prompts a UI pop-up for doing login). And on Lin/mac, folks would usually already have a git-configuration.

Another alternative is making azd to validate the git-local-config.
Either by introducing a command like `azd config check-local-git` which would remove/fix the current git-local-config for the project. Or by making this check to be something similar to the version-check routine, which execute on the background.
Doing this, we would keep the git-config-strategy still working everywhere, and will also have a way to repair cases like the one on this issue.

**Comment by vhvb1989** [comment]
@rajeshkamal5050 , I've moved this to 1.2.0, since I need some input about what we want to do here.

**Comment by savannahostrowski** [comment]
We definitely want to retain the end-to-end flows in Codespaces. I'd rather not expose a new command under config to handle this scenario.

> One alternative is to apply the git-credential strategy only when azd is running on codespaces.
The side impact would be reduced to only azd-users on Win/Lin/mac who are not already using git+.ssh keys and/or a credential manager to keep their https token-credentials.
This is a limited audience, IMHO, b/c installing git-for-windows installs a windows-credential-manager by default (which even prompts a UI pop-up for doing login). And on Lin/mac, folks would usually already have a git-configuration.

I don't have any data to support this but I think I agree with your take on how prevalent this is. I'll let @ellismg weigh in on this too.

**Comment by ellismg** [comment]
> One alternative is to apply the git-credential strategy only when azd is running on codespaces.

I think this is reasonable.  In general, I have always been a bit nervous about the thing we are doing here because it feels like mucking with the user's machine is very surprising behavior.

Doing something specific for codespaces seems reasonable, I sort of see how this is less destructive since out of the box the environment is wrong and the codespaces are sort of ephmerial anyway.

However, I'd also be fine if we just stopped touching the git config at all and just passing `-c <key>=<value>` to all the git commands we needed to do as part of the pipeline flow (so it could auth) and then leave a follow up note to the user that they may need to configure authentication for their newly created private repository so they can push to it, with a link to an aka.ms link on how to do that.  In this case, the end user would understand completely what was going on.
