### ISSUE TITLE
Playwright test fail in todo-nodejs-mongo

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#246]
**Describe the issue:**
Playwright test fail. But it is a probabilistic failure, with a high probability of failure.
Besides, through investigation, we found that the `listId` in the request URL is missing when creating `item`，because the page data had not been loaded when creating `item`.

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/179486968-1a5463a2-ea7e-435f-ab56-197baeffca53.png)

**Test Environment:**
OS : Windows Desktop
Template: https://github.com/Azure-Samples/todo-nodejs-mongo

In addition, in MAC and Linux environments, the test is passed most of the time。

**Repro steps:**
1.Run command `azd up`
2.Run command `cd tests`
3.Run command `npm i && npx playwright install`
4.Run command `npx playwright test`

**Expected behavior:**
playwright test can success.

@jongio,@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a quick look at see if it is indeed an issue?

**Comment by rajeshkamal5050** [comment]
@v-xuto @v-jiaodi 

The issue reported here seems to be similar to this one https://github.com/Azure/azure-dev/issues/291.
Given that it is passing in Mac and Linux. Don't think it should be an issue with the template.
- What happens when you try it manually?
- Can you please find out more on why it is failing?

Maybe we need to just fix tests to accommodate environments specific stuff. Similar to how we did fix on the tests for the other issue.

**Comment by v-jiaodi** [comment]
@rajeshkamal5050
+ The test is passed most of the time in MAC and Linux environments. But the same error occasionally occur.
+ It passes when we execute manually.
+ It is not similar to this one [#291](https://github.com/Azure/azure-dev/issues/291). Through investigation, we found because the page data loading is delayed, the `listId` in the request URL is missing when creating `item`. 
Besides, we have created a [PR](https://github.com/Azure-Samples/todo-nodejs-mongo/pull/2) to fix it. Please help review it.
