### ISSUE TITLE
Updates to ASA template - ReadMe, Pipeline Configs etc

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2503]

**Comment by vhvb1989** [comment]
@yiliuTo , use this for all ASA templates mentioned in this issue
https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/13#issuecomment-1650620687

**Comment by yiliuTo** [comment]
Hi @vhvb1989 thanks for helping modifying the devcontainer and github actions, and I have merged your PR to adopt the commit.
Besides, for the other 4 ASA templates, since we doesn't provide the support of dev container or github actions in the current stage, thus we cannot apply the modification to them. Thanks again!

**Comment by vhvb1989** [comment]
@yiliuTo , I think the only missing is: https://github.com/Azure-Samples/ASA-Samples-Web-Application/pull/19

You just need to apply the same changes to that one

**Comment by yiliuTo** [comment]
> @yiliuTo , I think the only missing is: [Azure-Samples/ASA-Samples-Web-Application#19](https://github.com/Azure-Samples/ASA-Samples-Web-Application/pull/19)
> 
> You just need to apply the same changes to that one

@vhvb1989 sure
