### ISSUE TITLE
Improve UX of flowing API keys/env vars through infrastructure

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2739]
Today, setting API keys as environment variables on infra is pretty convoluted --> e.g. copy the contents of your `.env` into the `.azure/<env name>/.env` file, add them to `main.parameters.json`, add params for the keys in `main.bicep`, pass params into `api.bicep` module and use in `api.bicep` secrets. 

Talking to @ellismg and @weikanglim about this it seems like we might want to investigate how we leverage Key Vault more heavily here.

Internal link to [pain points doc](https://microsoft-my.sharepoint.com/:w:/p/diberry/Ee7PhTLARGFBpoeW3NYL_YEBuaCJ5a6icHIeKSDZRVOwbg?e=IXDrRr&clickparams=eyAiWC1BcHBOYW1lIiA6ICJNaWNyb3NvZnQgT3V0bG9vayIsICJYLUFwcFZlcnNpb24iIDogIjE2LjAuMTY4MjcuMjAwNTYiLCAiT1MiIDogIldpbmRvd3MiIH0%3D&CID=202B3B78-C530-4134-9D1D-1B5913DC1172&wdLOR=c585308B2-E066-4B41-8B0A-0B45070686F8)

**Comment by weikanglim** [comment]
> investigate how we leverage Key Vault more heavily here.

Unfortunately, after some thought, I don't think this can be done easily without expanding azd's infrastructure provision to include a KeyVault seeding state.

The best short term is likely to source from `.env` / environment variables. I have a PoC [here](https://github.com/savannahostrowski/cinest/pull/2) that simplifies it to just defining the settings in `main.parameters.json`, in a format like:

```json
    "apiSettings": {
      "value": {
        "settings": [
          {
            "name": "openaiApiKey",
            "value": "${OPENAI_API_KEY}",
            "secret": true
          },
          {
            "name": "omdbApiKey",
            "value": "${OMDB_API_KEY}",
            "secret": true
          }
        ]
      }
  }
```

The extra node for `settings` is required since `@secure()` can only be applied to bicep `object`s at this time.

But with this change, users can either do `azd env set` or move configuration into `.env`, and only need to define it in `main.parameters.json`.

**Comment by savannahostrowski** [comment]
Look at that POC, we could generate all but what's in the main.parameters.json right? So then the user only really has to touch that single file or use azd env set to pass the keys?

**Comment by weikanglim** [comment]
Correct. User has to provide the value via env set, then wire up in main.parameters.json, but that's it.

I think this aligns with what @ellismg mentioned to me as what we can do short-term in passing as well.

**Comment by savannahostrowski** [comment]
I mean, that's much better than what we have today.

Longer term, it'd be nice if we could have a gesture to eliminate having to touch the Bicep at all but this is a start.

**Comment by vhvb1989** [comment]
using `file.parametes.json` won't work for the `bicepparams` approach

**Comment by weikanglim** [comment]
@vhvb1989 There's a direct translation to make this work in `bicepparams` world. The change hasn't been made to switch over, since we currently depend on `secretsOrRandom` for PostgreSQL
