### ISSUE TITLE
Do not display endpoints for resources without a public endpoint

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#280]
A resource can be provisioned and deployed without a public Url (no ingress).
For such cases, azd should not print empty endpoints

See https://github.com/Azure/azure-dev-original/issues/1430 as an example.

**Comment by rajeshkamal5050** [comment]
@v-xuto can you see if this is still the case?

**Comment by jianingwang123** [comment]
@vhvb1989 Based on the test results of the example [Azure/azure-dev-pr#1430](https://github.com/Azure/azure-dev-pr/issues/1430), `azd` does not print empty endpoints. This issue is no longer reproduced. The following is the output:

![Image](https://github.com/user-attachments/assets/43598704-3647-4871-866c-7e8289084662)

**Comment by vhvb1989** [comment]
thank you @jianingwang123 . I'll close this now
