### ISSUE TITLE
[Issue] azd pipeline config fails with error [codespaces]

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-dev#2851]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.4.1 (commit 1cbed85cf47ed235b5ed31868eda79619525bfcc)

**Describe the bug**
`azd pipeline config` and `azd pipeline config --auth-type client-credentials` both results in an error when ran in Codespaces (though the issue doesn't seem to be directly related):

```
$ azd pipeline config

Configure your GitHub pipeline

  (✓) Done: Checking current directory for Git repository

ERROR: service principal with client id '82a0a0d9-3a5a-4256-8307-8aa804c039cc' specified in environment variable 'AZURE_PIPELINE_CLIENT_ID' was not found
```

**To Reproduce**
I'm trying to setup the pipeline for https://github.com/Azure-Samples/azure-search-openai-javascript

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you triage it?

**Comment by vhvb1989** [comment]
@sinedied , `azd pipeline config` is not 100% supported from codespaces. See: https://learn.microsoft.com/azure/developer/azure-developer-cli/troubleshoot?tabs=Browser#solution-6

The workaround we have running `azd auth login --use-device-code=false` should help you to make `azd pipeline config` work, but it is not recommended.

**Comment by sinedied** [comment]
@vhvb1989 Thanks for the hint! `azd pipeline config` worked when disabling the device code.

But then even if the setup was successful, our CD still fails with a `401` error: https://github.com/Azure-Samples/azure-search-openai-javascript/actions/runs/6575825133/job/17863849594
Do you have any idea why?

Note that `azd up` works fine in Codespaces after logging in.

**Comment by vhvb1989** [comment]
@sinedied , I suspect that the problem is related to the ServicePrincial is not authorized within the Azure-Samples org.

Ideally, you don't want to use the Azure-Samples/repo-name to keep a Github-action, as the sample-repo typically acts as a template.  A user uses the template to create their app instance, and for setting up their own repository where they can add CI.

When we think about a template repo (like Azure-Samples/foo) with a CI for deployment, there are a couple of questions, like:
  - Who set/maintain the tenant/subscription where the app is deployed
  - Is FederatedCredential enabled for Azure-Samples org?
  - Do you want to keep an application instance always live and running (hosting open-ai service, 24x7)?

Maybe try creating your own private repo to test the pipeline. When running `azd pipeline config`, you can select the option to create a new private repository.
