### ISSUE TITLE
`--cwd` parameter not honored in Codespaces

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#2946]
- [ X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.4.3 (commit d165bd2de96dae75de57604c0d8a5553ae214618)

**Describe the bug**
I'm trying to run azd in a bash console in Codespaces. 
For this scenario I need to use the `--cwd` parameter to tell it to use a sub-directory. 

However, when I specify `--cwd azdtest` it is defaulting to the current directory, not the azdtest directory.
![image](https://github.com/Azure/azure-dev/assets/74415662/fd2f79ba-7c0e-4332-9b1c-df6850798e1f)

**To Reproduce**
1. create a subdirectory called `azdtest`
2. run `azd init --cwd azdtest --template azure-django-postgres-addon-aca`

**Expected behavior**
I expect azd to initialize the template into the specified directory.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by vhvb1989** [comment]
The root cause of this issue is trying to initialize a new azd-project within a folder which already contains an azd-project.

azd tries to find the project (azure.yaml) within the current folder AND within all the parent folders.  This is to enable running azd commands from within any folder inside the project (similar to how it is for git).

the `cwd` should probably change this behavior and prevent azd from walking the parent's folder to discover the project.

**Comment by ellismg** [comment]
It is a bummer that the logic that does the os.Chrdir for `cwd` doesn't happen before the project loading stuff.  I suspect this is an artifact of our use of DI.

**Comment by vhvb1989** [comment]
I haven't looked deep into it, @ellismg, but I am suspecting that the logic for `cwd` is happening first, as we expect. The problem comes after that, once azd is on the targeted cwd, it tries to see if there is an `azure.yml` in there (or within a parent folder) and that's when azd would switch back to the root folder, if an azure.yaml is found

**Comment by weikanglim** [comment]
This is a recent regression. The behavior works correctly on 1.3.1, regressed in 1.4.0:

https://github.com/Azure/azure-dev/blame/main/cli/azd/cmd/init.go#L128-L32

`init` should not be using a resolved `azdContext`. The old behavior was to always create an `azdContext` with the working directory specified.
