### ISSUE TITLE
[Issue] Core template versioning

### ISSUE THREAD

**Issue by diberry** [Azure/azure-dev#2999]
Can you add metadata/comments to the azd infra core files to version them?

**Comment by vhvb1989** [comment]
At some point in the past, we were planning to push all the bicep modules from core into a public registry, where you could see the version.
But the strategy changed towards the use of AVM (https://azure.github.io/Azure-Verified-Modules/)

Now the plan is to migrate azd-templates to use AVM instead of the azd-core modules.

**Comment by dfberry** [comment]
@vhvb1989 What is the timeframe for migration?

**Comment by jongio** [comment]
Migration to avm being tracked here: https://github.com/Azure/Azure-Verified-Modules/issues/261

It is likely months away.

In the meantime, it would be nice to have a comment in the header of each bicep file with the current version.  @danieljurek thoughts?
