### ISSUE TITLE
[Issue] Doesn't check for globally installed bicep-cli

### ISSUE THREAD

**Issue by Tanish2002** [Azure/azure-dev#3019]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
azd downloads and stores the bicep-cli in `~/.azd/bin`. However in a case where it's already installed on the system and available on `PATH`. It still just checks that specific directory and downloads it if not available.

**Expected behavior**
If `bicep` command is already available on `PATH` then skip the download.

**Environment**
NixOS
Linux anime 6.1.60-xanmod1

**Comment by weikanglim** [comment]
@Tanish2002 Thanks for raising this! There is an environment variable `AZD_BICEP_TOOL_PATH` that can be overridden to choose a different bicep installation, if that works for you. We were initially avoiding dependencies to global installations since that can lead to more user friction around package management.

**Comment by Tanish2002** [comment]
Thanks for the pointer! I didn't know there was such a variable available. 
This probably needs some documentation(or it already is and I missed it).

Closing the issue!
