### ISSUE TITLE
When running `azd init` on a non-Aspire directory it gives an incorrect error message

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#3024]
_transfered from https://github.com/dotnet/aspire/issues/930_

**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
When running `azd init` on a solution that has an Aspire app it detects it but kinda gives a wrong helpful error:
`ERROR: only a single Aspire project is supported at this time`

If navigating to the correct AppHost directory and run init it works.  The error is misleading and generates confusion.

**To Reproduce**

1. Create new Aspire blank app from VS
2. Add project, choose Blazor, select Server and WebAssembly for interactive mode from VS
3. Build solution
4. Open CLI and navigate to the solution root
5. `azd init`

**Expected behavior**
A helpful error message indicating that nothing could be found or if detecting an Aspire app but the wrong location, provide a helpful hint to the right location

**Comment by ellismg** [comment]
The issue here is that during `init` we walk from the root (i.e where `azd init` was run) and discover all the projects under that location.  From this set, we look to see if there is a .NET Aspire AppHost, and if so, we remove all the projects references by the AppHost from our set of discovered projects (since they are "managed" by the Aspire app).

Once that is complete, if the set of projects contains an app host and there are still additional projects, we error out, because we have not yet designed how an Aspire app would integrate with a set of unmanaged projects.

In this case, it sounds like what is happening is the new Blazor project has not been referenced by the AppHost  (via .AddProject) and so we don't remove it from the list of discovered projects.

In the short term, we could improve the UX here.  If the set of detected projects includes an Aspire project and there are others, we could, for example print a warning message that we are in this state and ignoring the non aspire projects, and tell the user they should consider putting some `.AddProject()` calls in their app host.

I think we want to push users to run `azd init` in the root of their project, not their app host folder, since we want to have the azd project root mirror the root of the user's project.

**Comment by timheuer** [comment]
Interesting @ellismg -- given this I would have expected same error message if I have a project that is just a classlibrary, but it doesn't.  In the Blazor instance, the BlazorClient project is referenced into the BlazerServer project and wouldn't be added independently to the AppHost.

So the following works:
- apphost (with reference to web project)
- web project (with project reference to class lib)
- class library

But the blazor one does not...what's special about the Blazor layout that is tripping up init, but the classlib one is not?

**Comment by weikanglim** [comment]
@timheuer azd skips detection for class libraries which is what you're seeing, since we're detecting for "hostable applications". Currently, this is done very naively by looking at projects with a presence of a startup file that looks like Program.cs. We could update this logic to use `dotnet msbuild --getProperty:OutputType` now that there's an easy way to query for MSBuild properties without additional parsing. However, for the BlazorClient assembly project, the property is still marked as `exe` based on my testing. We can update the detection logic to treat Blazor web client assemblies as "non-hostable", or maybe there's a more definitive way for all dotnet projects -- since `OutputType` wouldn't work in this case. Do you have suggestions here?

**Comment by timheuer** [comment]
is there a reason we don't just look for `IsAspireHost` ?

**Comment by timheuer** [comment]
My bad, sorry :-)

One nuance is that a blazor client project could be a static hosted thing itself (e.g., you can just jam it in Storage, Static Web Apps, or App Service Windows works as well)...but those are maybe more rare...

Other identifiers for blazor client:
- SDK == Microsoft.NET.Sdk.BlazorWebAssembly
- NoDefaultLaunchSettingsFile = true

@DamianEdwards any ideas to identify a BlazorClient one to think about making this detection logic smoother?

**Comment by DamianEdwards** [comment]
Adding @danroth27 too.

It doesn't have to be something in the project file directly, it can be any MSBuild property or item that is present after project evaluation. The Blazor WebAssembly SDK sets MSBuild property `<UsingMicrosoftNETSdkBlazorWebAssembly>true</UsingMicrosoftNETSdkBlazorWebAssembly>` so checking for that is likely enough to detect a Blazor client project. There's also `<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>` which could be used in addition or instead.

**Comment by danroth27** [comment]
Blazor Web Apps currently host the client WebAssembly-based project as static web assets in the server project that references it. The client project isn't really intended to be hosted separately at this point. We've talked about enabling that scenario, but it's still in the discussion/prototyping phase.
