### ISSUE TITLE
Aspire: Support azure.appconfiguration.v0

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3064]

**Comment by vhvb1989** [comment]
Moving this to Jan/24 as appconfig is not expected for Aspire preview2

**Comment by rajeshkamal5050** [comment]
Depends on https://github.com/dotnet/aspire/issues/787. Moving this to the Germanium semester bucket. We can pull it into appropriate milestones based on aspire dependency updates and priority.

@ellismg @vhvb1989 since the azd changes are done https://github.com/Azure/azure-dev/pull/3078. Can we hide and keep it under feature toggled off i.e., `unsupported resource type: azure.appconfiguration.v0`?

@davidfowl @mitchdenny
