### ISSUE TITLE
Terraform templates failed to execute `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3080]
**Describe the issue:**
Test `todo-nodejs-mongo-terraform` template on US Gov Cloud. Run `azd up`, get error as follow：

![image](https://github.com/Azure/azure-dev/assets/80496810/6c1f9475-056d-47d5-ad45-38e1b37c59c6)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-nodejs-mongo-terraform`.
3. Login Azure CLI with command: `az login`.
4. Run `azd up`.

**Environment:**

- Cloud: US Gov.
- Template: todo-nodejs-mongo-terraform, todo-python-mongo-terraform.
- Azd version : 1.6.0-beta.1  (commit https://github.com/Azure/azure-dev/commit/04fedb57ba251d0c7cfdc8e3612cdf35ee6c04f8)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek   for notification.

**Comment by danieljurek** [comment]
This may be mitigated by setting az CLI in the appropriate cloud mode. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli#logging-into-the-azure-cli 

I will test.

**Comment by danieljurek** [comment]
Provision and deploy both succeed when `az` CLI is configured to use US Gov Cloud and the environment variable `ARM_ENVIRONMENT` is `usgovernment`. If these are done outside then the deployment succeeds. 


However, our Terraform templates have a cycle when app services are used. The value for `REACT_APP_API_BASE_URL` in the _web_ app and `API_ALLOW_ORIGINS` in the _api_ app require that the other be deployed. Today this issue is addressed by hardcoding the domain suffix. 

Two possible fixes: 
1. `azd` provides a domain suffix var of some sort to terraform (this seems particularly bad as this would couple templates to azd unnecessarily) 
2. Some internal terraform method of resolving these
3. Document the issue

**Comment by danieljurek** [comment]
It may be possible to use a `local-exec` "resource" in Terraform to modify `api`'s configuration after `web` and `api` have deployed successfully.

**Comment by v-jiaodi** [comment]
@danieljurek According to `AzdManualTestSovereignClouds.docx` and The above comments，terraform templates can deploy successfully.

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3481
