### ISSUE TITLE
Add C#, SQL, SWA, Func App Todo App Template

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#316]
1. Convert this to function https://github.com/Azure/azure-dev/tree/main/templates/todo/api/csharp-cosmos-sql

**Comment by madebygps** [comment]
Here is the PR, apologies for delay, hold up was due to https://github.com/Azure/azure-functions-host/issues/8311. Deploying the Linux consumption is still not possible, but the team said using windows consumption would be fine and the template works for that. Once the Functions teams resolved the host issues, I can update the template work deploy to Linux consumption.
