### ISSUE TITLE
DEMO Mode - Hide subscription ID 

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-dev#319]
Need to have demo mode option to hide/obscure sub ids.

**Comment by pgadige** [comment]
@savannahostrowski I am working on this. I shall submit a draft PR for review shortly.

**Comment by isaacrlevin** [comment]
@ellismg I just took a look at this and it isn't very straightforward to mask out the subscription ID based on a handful of reasons.

- The sub ID is retrieved and than stored in a string [here](https://github.com/Azure/azure-dev/blob/f00f37d70ae38a8b53d28650b0398ea4d097ec7d/cli/azd/pkg/prompt/prompter.go#L174)
- That string is than passed to the user for selection and parsed [here](https://github.com/Azure/azure-dev/blob/f00f37d70ae38a8b53d28650b0398ea4d097ec7d/cli/azd/pkg/prompt/prompter.go#L75)

The problem with this approach is that the value of the subscription ID is not stored in a way that you can simply masking it from the user. In order to do that, you would need to have a instead of storing the sub name and id as a string, it would need to be in a class where you can mask the ID that goes to the user without losing the actual value.

**Comment by timheuer** [comment]
Yeah @isaacrlevin The goal here would be to mask in presentation not storage. So wherever writing to console it masks it at that point. I think there are a few places where a common ‘console write’ happens and masking the var at that time would do the trick
