### ISSUE TITLE
Terraform templates failed to execute `azd up` on China Cloud

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-dev#3228]
**Describe the issue:**
Test `todo-nodejs-mongo-terraform`/`todo-python-mongo-terraform` templates on China Cloud. Run `azd up`, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/57525824/75395bd6-86c9-4a17-8fe4-e5498b5138e6)

**Repro Steps:**

1. Set enviroment variable `ARM_ENVIRONMENT` to "china".
2. Run `azd config set cloud.name AzureChinaCloud`.
3. Login in with command: `azd auth login`.
4. Execute command: `azd init -t todo-nodejs-mongo-terraform --branch pr/2897`.
5. Run `azd up`.

**Environment:**

- Cloud: China.
- Template: `todo-nodejs-mongo-terraform`, `todo-python-mongo-terraform`.
- Azd version : 1.6.0-beta.1-pr.3436205 (commit 79ee6dfcae682672d0808d2590b93d298fcba844)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek for notification.

**Comment by danieljurek** [comment]
@dotnet-7 -- Does this reproduce if the following are done: 
* Install `az` CLI, log into china cloud on az cli (`az cloud set --name AzureChinaCloud` and `az login`)
* Set environment variable `$env:ARM_ENVIRONMENT='china'`

I was able to get a successful deployment using 

`azd.exe init -t todo-nodejs-mongo-terraform --branch pr/3452`

Note that the PR number and branch name (`--branch pr/3452`) have changed from when this bug was opened

**Comment by v-jiaodi** [comment]
@danieljurek Which version of `azd` should I use?  
Install `pr/2897` version, get error : `BlobNotFoundThe specified blob does not exist`.
Using `pr/3453` version, when run `azd auth login` after run `azd config set cloud.name AzureChinaCloud`, unable to switch to `ChinaCloud`.

**Comment by danieljurek** [comment]
We don't have a reliable build for https://github.com/Azure/azure-dev/pull/3452/files yet, but when we do that will be where azd should be installed from to test this scenario. 

Hold on until we get that done.

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3481
