### ISSUE TITLE
[Aspire] Secret inputs? Handle same as connection strings and store as container secrets

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#3265]
When deploying a container.v0 resource which references a {resource.inputs.someValue} and the someValue is defined as being a secret, AZD puts the value in clear text in the enivronment variables. I think we should give any inputs that are marked as a secret the same kind of treatment as connection strings and store them as a container secret so they aren't easy to get to.

cc: @ellismg @davidfowl @mitchdenny

**Comment by ellismg** [comment]
Yes - when we did the `generate` stuff for preview 2 we ended up just storing the values in the `.env` file and passing them directly as that was the quickest path forward and we weren't sure what the end to end secrets story was looking like in Aspire.  We should fix this now for the stuff we are `generate`ing and then ensure when we have prompting for secret inputs they are also stored securely in ACA.

Long term, we should think about if we should be storing these values in our `.env` at all - I think they need to be in KeyVault instead of us storing them on disk - and then ACA either references them from that keyvault (i.e we use the same one as the application) or we migrate them during a deployment from one keyvault (i.e. you `azd` keyvault, which is project wide and stores just the secrets that `azd` needs to store to the one provisioned as part of the app).
