### ISSUE TITLE
azd up publishes Debug builds instead of Release builds (.NET Aspire)

### ISSUE THREAD

**Issue by christiannagel** [Azure/azure-dev#3436]
Since .NET 8, the default build configuration with `dotnet publish` is a Release build. 
I think this should also be the default for `azd up` as well. Instead, using `azd up` creates a Debug build.

Using the --debug option of azd (which I think is the equivalent of -d (--diagnostics) with the dotnet CLI, I can see this command where the -c option is explicitly set to Debug:

```bash
dotnet publish D:\codebreaker\ch12b\Pragmatic-Microservices-with-CSharp-and-Azure\ch12\Codebreaker.GameAPIs\Codebreaker.GameAPIs.csproj -r linux-x64 -c Debug -p:PublishProfile=DefaultContainer -p:ContainerImageName=azd-deploy-gameapis-1708853612 -p:ContainerRegistry=<redacted>
```

Also, without the `--debug` option, the debug builds are built and published.

Versions:
azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)
aspire 8.0.0-preview.3.24105.21/8.0.100

**Comment by baronfel** [comment]
We highly recommend publishing in release mode for all deployment tools, `azd` included! While `Release` is the default for .NET 8, since `azd` may support more than the .NET 8 SDK I'd probably go with making it explicit and specifying `-c Release` in your publish command. It [looks like](https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/tools/dotnet/dotnet.go#L110-L112) a user can supply a configuration already, but I'd lean into a safer default of `Release` if the user doesn't explicitly specify.
