### ISSUE TITLE
Supporting Several Aspire Host Projects in a single VS solution

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#3563]
From @abpiskunov offline - Corner case scenario where there could be several Aspire Host projects and VS has added some support to let user pick one. In deployment scenario we already explicitly in some host project since user opened a Publish designer for it.

Scenario:

1. A user working with Aspire projects in VS has added two AppHost projects within the same solution.
2. The user attempts to right click and Publish on each project.
3. The user expects that this is possible, and each project should work independently.

Proposal:

1. When azd detects that a project is being published, that is different than the one in the solution directory, azd will create an  `azure.yaml` in the apphost project directory.
2. This will allow publishing to work. This also allows `azd` commands to work correctly in the apphost project directory.
3. This will not allow `azd` commands to work in all service project directories, a long-term proposal related to #3789 is required.

**Comment by vhvb1989** [comment]
I think this impacts azd easy init, azd needs to list and ask the user which appHost to use, instead of returning an error

**Comment by weikanglim** [comment]
My preliminary thoughts:

I'm wondering how multiple apphost projects would be structured. Ideally, they're treated as different deployable application from azd's perspective. In this case, we'd want an azure.yaml per apphost project.

In a scenario where the file structure looks like:

```yaml
- Solution/
   - App1/
     - azure.yaml
     - App1.AppHost/
     - App1.Api/
   - App2/
     - azure.yaml
     - App2.AppHost/
     - App2.Api/
```

This would work nicely. When VS calls `InitializeSessionAsync`, you could pass the "hostProjectPath" for `Solution/App1` and `Solution/App2` respectively. Since all other calls past this references the session, we wouldn't need to update all the contracts.

The one restriction here from azd right now is that azure.yaml file "should be located above the projects being referenced". In a case where:

```yaml
- Solution
   - App1.AppHost/
   - App1.Api/
   - App2.AppHost/
   - App2.Api/
```

I'm not sure how we could handle this yet.

**Comment by rajeshkamal5050** [comment]
Multiple app host projects in a solution is not supported and is out-of-scope for Aspire 8.0/GA

**Comment by christiannagel** [comment]
Please think about this scenario with one solution:

```
- Solution
  - App.Azure.AppHost
  - App.Prometheus.AppHost
  - App.Service1
  - App.Service2 
```

Where both AppHost projects reference the same service projects but have different app-models. The Azure AppHost uses AppConfiguration, KeyVault, App Configuration..., whereas the Prometheus AppHost uses Docker containers for Prometheus and Grafana.
