### ISSUE TITLE
Add support for getting endpoints for Azure Functions based services

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#358]
In Azure/azure-dev-pr#627 we are adding support so that during a `deploy`, we print endpoints for all the services we deploy.  Some (but not all) Azure Functions services can have endpoint (every azure function with an HttpTrigger will have an endpoint).

Today we just don't list endpoints for services deployed to Azure functions.  This item tracks fixing that by actually implementing the `Endpoints()` method on `project.functionServiceTarget` instead of just returning `nil, nil` as we do today.

Here's a sketch of a possible implementation strategy, taking from a comment while I was doing the initial PR (after I did some investigation into it):

```golang
// TODO(ellismg): Implement this. It's not 100% clear what this should do, since a functions app may not include
// any HTTP based services (consider an event driven application where the trigger is "some blob was created" or
// "a message was put into a Azure Storage Queue").
//
// One possible idea would be to enumerate all of the functions in your application that have HTTP triggers, and return
// them here (perhaps with their invoke keys?)
//
// The `az` CLI does not provide an out of the box way to list the functions in a function app. This is something you
// can get via the `func` CLI - but the output is designed for humans, not computers, so we may want to do something
// like what was recommended here: https://stackoverflow.com/a/45111951
//
// That would look something like:
//
// az rest --method get --url "/subscriptions/{sub_id}/resourceGroups/{rg_name}/providers/Microsoft.Web/sites/{function-app-name}/functions?api-version=2015-08-01" --output json
//
// and then use the `values` array to pull stuff out. Note that this list endpoint is pageable, so we would likely
// need to handle following the pageable ourselves.
```

**Comment by rajeshkamal5050** [comment]
Might have already been handled. 

Based on the below deployment of `Azure-Samples/todo-python-mongo-swa-func`. Able to see the functions app endpoint.

```
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  You can view detailed progress in the Azure Portal:

  (✓) Done: Resource group: rg-rg-raj-del
  (✓) Done: Static Web App: stapp-web-3sx5vmzillpxy
  (✓) Done: App Service plan: plan-3sx5vmzillpxy
  (✓) Done: Log Analytics workspace: log-3sx5vmzillpxy
  (✓) Done: Key vault: kv-3sx5vmzillpxy
  (✓) Done: Storage account: st3sx5vmzillpxy
  (✓) Done: Application Insights: appi-3sx5vmzillpxy
  (✓) Done: Portal dashboard: dash-3sx5vmzillpxy
  (✓) Done: Azure Cosmos DB: cosmos-3sx5vmzillpxy
  (✓) Done: Function App: func-api-3sx5vmzillpxy


Deploying services (azd deploy)

  (✓) Done: Deploying service api
  - Endpoint: https://func-api-3sx5vmzillpxy.azurewebsites.net/
  (✓) Done: Deploying service web
  - Endpoint: https://salmon-moss-0d51e560f.2.azurestaticapps.net/
```

**Comment by spboyer** [comment]
This is not fixed. The comment above from @rajeshkamal5050 shows the root endpoint and not the individual function endpoints.

Currently, when you deploy an Azure Function App using `azd`, the CLI only reports the base URL of the Function App (e.g., `https://<app-name>.azurewebsites.net/` as noted in comment above). It does not list the specific endpoints for the functions you just deployed (e.g., `https://<app-name>.azurewebsites.net/api/MyHttpTrigger`).

This forces users to manually construct the URL or go to the Azure Portal to find the correct endpoint to test their function, which breaks the "inner loop" development flow.

Code Context
The issue is explicitly referenced in `service_target_functionapp.go`

```
// Gets the exposed endpoints for the Function App
func (f *functionAppTarget) Endpoints(...) ([]string, error) {
    // TODO(azure/azure-dev#670) Implement this. For now we just return an empty set of endpoints...
    // ...
    // (Current implementation only returns the base HostName)
}
```

Recommended Fix
To address this, the `Endpoints` method needs to be updated to:

Query the Azure Management API (or Kudu) to list the functions within the app.
Filter for HTTP-triggered functions.
Construct the full invocation URL for each function (including any required function keys if auth
is enabled).

**Comment by vhvb1989** [comment]
I'll take a look to this one. Thank you for re-opening @spboyer
