### ISSUE TITLE
Unsupported resource type azure.openai.account.v0

### ISSUE THREAD

**Issue by markjbrown** [Azure/azure-dev#3640]
I am getting this error when I run azd init for eShop.

I have multiple AOAI accounts in my subscription. It blocks completion so cannot run azd up after this error. Also filed bug on eShop
https://github.com/dotnet/eShop/issues/276

![image](https://github.com/Azure/azure-dev/assets/800166/7ee6ca2b-9ee3-4ea4-92c0-9a32e1c0d682)

**Comment by rajeshkamal5050** [comment]
@markjbrown this has been fixed in the upcoming Preview 5 release. Has more context on the issue - https://github.com/Azure/azure-dev/pull/3547

You can wait for the Preview 5 release(Apr 9) or try latest aspire bits from preview 5 branch + [daily bits of azd](https://github.com/Azure/azure-dev/tree/main/cli/installer#download-from-daily-builds)

cc @mitchdenny @vhvb1989

**Comment by markjbrown** [comment]
I downloaded and retried this using daily bits and got the same error. can you please reopen this?

See confirmation of error and azd version below.

cc @rajeshkamal5050 @mitchdenny @vhvb1989 

![image](https://github.com/Azure/azure-dev/assets/800166/4ed44185-9a27-4229-a8af-4822b0e52881)
![image](https://github.com/Azure/azure-dev/assets/800166/829c897c-dec0-4d0d-bb62-5fa7fbfc6463)

**Comment by vhvb1989** [comment]
@markjbrown , make sure you are using the preview5 branch from the eShop: https://github.com/dotnet/eShop/tree/aspire-preview5

Otherwise the project will be using aspire prev4,

**Comment by markjbrown** [comment]
thanks @vhvb1989. I pulled down that branch and I'm now getting this error.

![image](https://github.com/Azure/azure-dev/assets/800166/7286b964-0c06-49fc-a1ac-2dfd5bf21eb0)
