### ISSUE TITLE
[Issue] Support secretOrRandomPassword in terraform deployments

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-dev#3832]
The current (1.8.1) version of azd with the terraform provider does not provide a similar capability as secretOrRandomPassword.

Can you please provide some guidance on how we can get the similar functionality within Terraform.

**Comment by ellismg** [comment]
Instead of adding native support for this to `azd`, I would consider trying to use the [`random_string`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string) resource in Terraform.

This will allow a random value to be created and the value will be stored in the state file and re-used across deployments.  If you need this stored in KeyVault as well, as `secretOrRandomPassword` would do, you can use terraform to create that resource.

We built `secretOrRandomPassword` to address the fact that bicep has nothing like the `random_string` resource, so we needed something that behaved like this resource and stored the state somewhere.
