### ISSUE TITLE
[Issue] Can't get environment outputs when doing `azd env select` in devcenter mode

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-dev#3861]
In devcenter mode, I do an `azd env select <envname>` and when this occurs, an error is returned and the environment does not get set correctly.

![image](https://github.com/Azure/azure-dev/assets/522116/2adc1702-986b-4280-a0f9-4389502d9deb)

**Comment by ellismg** [comment]
We failed to discover the outputs here because we could not find the corresponding ARM deployment in the deployment history for the resource group attached to the environment.  That failed because there was a mismatch between what was in `azure.yaml` for `platform.config.environmentType` (which was Test) and what was tagged in the deployment object we intended to find (which was Dev).

I asked @markweitzel offline if he knew how these might have gotten out of sync.

It may be reasonable to say that you can `azd env select` an environment even if we couldn't find the corresponding deployment (I'll leave that as a question for @wbreza when he gets back, we allow this today outside of dev center mode) but even if we were to allow this `azd env refresh` would fail later in the end to end for @markweitzel's specific scenario, since there we really do need the deployment object to fetch the outputs.

After making the change to `azure.yaml` I was able to `azd env select` the environment and run `azd env refresh`.

**Comment by wbreza** [comment]
This is not intentional.  It looks like it is comparing the environment of the currently selected project instead of the matched remote ADE environments.
