### ISSUE TITLE
[Issue]When `azd auth login`, x509 error occured in WSL(ERROR: logging in: failed to authenticate: server response error:  Get "https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by RyosukeDTomita** [Azure/azure-dev#3882]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```shell
azd version
azd version 1.9.0 (commit 651394c3ddcfadff194d177f8b0ddf06fe3752bf)
```

**Describe the bug**
When I tried `azd auth login`, x509 error occured.
This error is occurring in WSL, not Windows Powershell.

```shell
azd auth login

ERROR: logging in: failed to authenticate: server response error:
 Get "https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**To Reproduce**

**Expected behavior**

**Environment**
Information on your environment:
 - OS: Windows 11
 - WSL: 2.1.5.0
 - Ubuntu(22.04.3 LTS (Jammy Jellyfish))→use azd auth login
 - azd: 1.9.0

**Additional context**

**Comment by ellismg** [comment]
There error here makes it sound like the TLS handshake failed because we didn't trust the CA of the presented certificate.  Is the [`ca-certificates`](https://packages.ubuntu.com/search?keywords=ca-certificates) package installed in WSL for you?

I wonder if `curl -v https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration` works and shows a successful validation of the certificate.

**Comment by RyosukeDTomita** [comment]
Today, I fix this problem.

This error was happened because our organization only allow the access through the own proxy server.
