### ISSUE TITLE
[Issue] `azd pipeline config` should also include github/azdo workflow file

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#4013]
azd init generates infra and azure.yaml, but doesn't include an azure-dev.yml github workflow file. 

I had to hunt that down on my own.

Would be nice if it included one.

**Comment by weikanglim** [comment]
I have always wondered if maybe `azd pipeline config` (or maybe a separate gesture like `azd pipeline init`?) would be the right place to provide a starter workflow for `azd`. I could see that:

- Maybe some users won't actually need CI/CD, and these extra files aren't well understood.
- Maybe some users would benefit from progressive disclosure to build up a better mental model instead of having all these things upfront.

Let's say if we were trying to implement this feature in `azd init` today. We probably would need to surface a question of whether Azure Pipelines or GitHub should be used if no folders were present.. But would users already understand what that means when `azd init` runs?

**Comment by jongio** [comment]
Having it be part of azd pipeline config would be fine:

"We noticed that you don't have a github workflow file, would you like to add one?"
