### ISSUE TITLE
[Feature request] Allow .azuredevops as well as .azdo folders

### ISSUE THREAD

**Issue by rick-roche** [Azure/azure-dev#4034]
Currently, `azd` looks for the [azure-dev.yml](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub#prerequisites) file in either:

- For GitHub Actions: in the `.github/workflows` directory.
- For Azure DevOps: in the `.azdo/pipelines` directory.

The ability to use [Azure DevOps pull request templates](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops) supports placing a template in the following directories - `.azuredevops`, `.vsts`, `docs` or the root of the repository.

As a result, we've implemented the convention of using `.azuredevops` as the directory where all our azdo components live. It would be great to be able to use either `.azdo` or `.azuredevops` directories with `azd`.

My proposal is to allow `azd` to be able to look for `azure-dev.yml` in either `.azdo/pipelines/azure-dev.yml` or `.azuredevops/pipelines/azure-dev.yml` folders when using Azure DevOps.

**Comment by johnnyreilly** [comment]
+1 from me.  A convention has grown up in many places (and, if memory serves, it originally grew out of how Microsoft would structure public Azure DevOps repos) of having the `.azuredevops` folder being the main folder for all things Azure DevOps related in the repo.  The equivalent of `.github` if you will.  I've noticed that an alternative convention of using `.azdo` is has become more common recently; and it looks like `azd` is embracing that.  

It would be awesome if it supported `.azuredevops` as well as `.azdo`.  Speaking for the organisation I work in, we could all move to use `.azdo` but it would be a slightly painful migration, given the retargeting of pipeline files / build validations etc.  Totally doable of course, but frankly a real chore.

Would *love* to see `.azuredevops` support in `azd` - as much as anything else, because it feels like a missing piece rather than a brand new feature. (I say this given the in built support for `.azuredevops` in the Azure DevOps platform itself.)

**Comment by jongio** [comment]
@rick-roche @johnnyreilly - Can you please try the build from this PR and validate if it meets your needs?  And if not, can you add comments to that PR?
https://github.com/Azure/azure-dev/pull/4190

**Comment by johnnyreilly** [comment]
Oh wow - thanks for taking a look at this! Apropos of nothing, I'm indebted to you elsewhere @jongio - you power the Auth that I use to ship my Azure Static Web Apps backed blog and even get a shout out in the [README](https://github.com/johnnyreilly/blog.johnnyreilly.com?tab=readme-ov-file#auth) 😅

I'm away on holiday right now but will be back in front of a computer next week - I can test then! From the looks of the PR we can just use:

```bash
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/4190/uninstall-azd.sh | bash;
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/4190/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/4190 --version '' --verbose --skip-verify
```

To test the PR build?

**Comment by rick-roche** [comment]
Hi @jongio , this is fantastic - thank you! This adds what I was hoping for and works as expected off the branch.

**Comment by peteraritchie** [comment]
Does this mean https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub can/should be updated?

**Comment by johnnyreilly** [comment]
Good shout! I've opened a docs PR here: https://github.com/MicrosoftDocs/azure-dev-docs/pull/1424
