### ISSUE TITLE
Fail to run `azd init` for `ADE Integration Test`

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#4277]
**Describe the issue:**
When running the command `azd init -t todo-nodejs-mongo -b staging`, it fails with the following error:
![image](https://github.com/user-attachments/assets/b65a0de3-b4ec-45da-9f05-90fa3d920e67)
At the same time, run the `azd template list` command, the result is as follows (empty):
![image](https://github.com/user-attachments/assets/9a761942-e614-4d0e-b3fe-ba6fdb769bbe)

**Repro Steps:**

1. Run `azd auth login`.
2. Run `azd  init -t https://github.com/wbreza/azd-devcenter`.
3. [Create github token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token).
4. Run `$env:GITHUB_TOKEN='<github_token>'`.
5. Run `azd up`.
6. Check whether the Status of catelog in the devcenter resource created on the portal is successful.
7. Add the following to the local `~/<user_profile>/.azd/config.json` file and replace `<Dev center>` with the name of the devcenter resource created:
```
"platform": {
	    "config": {
	      "name": "<Dev center>"
	    },
	    "type": "devcenter"
  },
```
8. Create a new folder and open the cmd command line or VS code.
9. Run `azd init -t todo-nodejs-mongo -b staging`.

**Environment:**

- Template: `todo-nodejs-mongo`, `todo-python-mongo-aca`.
- Azd version: `azd version 1.10.0-beta.1-daily.4086794 (commit 9445b193c91acfa2d4bcae129cb7471ecc101e11)`.
- OS: Windows.
- Branch: Staging.

**Expected behavior:**
`azd init -t todo-nodejs-mongo -b staging` command can run successfully.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@wbreza can you triage this?

**Comment by wbreza** [comment]
Hi @Menghua1 - It looks like you are creating an e2e integration test for azd + ADE.  There are a couple things that I noticed that should help.

1. Use the official template instead of my fork - https://github.com/azure-samples/azd-deployment-environments/

Run the following in regular azd mode to create a usable devcenter resource with example project configuration.

## Create DevCenter instance

```bash
# Create devcenter and required dependencies
azd init -t azd-deployment-environments
azd up
```

![Image](https://github.com/user-attachments/assets/850ccc03-0c7b-44a8-9afd-39dffc67c901)

## Configure `azd` for DevCenter

To connect to the new devcenter you can either set the azd configuration or use environment variables.

### Create with `azd` configuration

```bash
# Setup connection to your devcenter with azd config
azd config set platform.type devcenter
azd config set platform.config.name <devcenter-name>
```

### Create with environment variables

```bash
export AZD_PLATFORM_TYPE=devcenter
export AZURE_DEVCENTER_NAME=<devcenter-name>
```

Running `azd template list` will now show the available templates within your devcenter catalog

![Image](https://github.com/user-attachments/assets/904eb6b8-8924-4026-9eb1-c6360969c1a4)

## Create ADE deployment from `azd`

Now when running `azd init` and selecting the template option this will automatically pull down the available templates. Selecting a template will automatically download app code and configure your app to use the devcenter created in the steps above.

![Image](https://github.com/user-attachments/assets/7c75d7a3-af0e-4778-bcd8-b48be0c1b43a)

From this point run `azd up` to provision your app use Azure Deployment Environments (ADE)

**Comment by Menghua1** [comment]
@wbreza  We have tested again based on your [comments](https://github.com/Azure/azure-dev/issues/4277#issuecomment-329891164) and there is no current issue, thank you very much!
Finally, we will close the current issue.
