### ISSUE TITLE
Template-test CI pipeline is not creating `DeleteAfter` tag

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#481]
template test CI pipeline guess the resource name that will be created so it can create a tag for it at the end of the tests:

![image](https://user-images.githubusercontent.com/24213737/185009271-c0cef078-3409-4f2e-be67-0a6dfbbf9d27.png)

After updating templates to use the resource group name as `rg-{name}` by default instead of `{name}-rg` , all resources from the pipeline are leaked.

@danieljurek do we need to manually clean the current leaks?

**Comment by ellismg** [comment]
Instead of applying the tags after the fact using `az`, I wonder if we should figure out how to update our templates such that we can pass in an additional set of tags to apply to resources (or just the root resource group)?  Perhaps an optional parameter named `additionalTags` which takes an object of tag name/tag value pairs that we apply and the script can set this object to include a delete after tag?

**Comment by weikanglim** [comment]
I don't think we're leaking any resources according to the [resource management doc](https://github.com/Azure/azure-sdk-tools/blob/main/doc/engsys_resource_management.md#resource-groups) since the resources are not tagged with an alias.

However, it does delay deletion of these resources by 24 hours and we should be good citizens and remove resources that are unused.

**Comment by vhvb1989** [comment]
@weikanglim, I found many `resource groups` from about ~10 days ago:

![image](https://user-images.githubusercontent.com/24213737/185455222-c2972aa7-6697-4b75-9d19-0f3f2cf01f65.png)

@benbp , are those resources going to be automatically deleted?

**Comment by benbp** [comment]
@vhvb1989 I have not enabled aggressive deletion of groups yet, hence why you are still seeing untagged+unaliased groups not being deleted. Setting the DeleteAfter tag is the right thing to do.

**Comment by ellismg** [comment]
> Perhaps an optional parameter named `additionalTags` which takes an object of tag name/tag value pairs that we apply and the script can set this object to include a delete after tag?

FWIW (Ben hints at it here) - Our internal playground subscription requires that either the resource group you create begins with your MSFT alias *or* some special tag is applied.  Otherwise the resource groups are subject to periodic deletion.  Since our templates use `rg-` as the prefix for all resource groups (per the convention outlined in https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming) it means that long term we'd want to be tagging the resource group with some tag.

This is specific to our team's developer workflow (so changing our templates to suit it feels wrong) but is a place we would leverage `additionalTags` if we had it.
