### ISSUE TITLE
[Issue] Link to portal progress on `azd provision` yields "could not be found"

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#490]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.1.0-beta.4 (commit fd96b3e9b283598bc4dc736e893f1b47080fbf7d)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
```
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.25.0"
  }
}
```

**Describe the bug**
When I run `azd provision` and click the link that shows progress in the Portal, I run into a "could not be found" even after the I see that resources have been provisioned in the CLI output.
![image](https://user-images.githubusercontent.com/8949415/185483787-4ff73b39-6305-4b9c-acac-d841e80f01c3.png)

![image](https://user-images.githubusercontent.com/8949415/185483680-105d3555-0ce1-48a0-896e-c846629a1ff1.png)

**To Reproduce**
1. Run `azd provision`
2. Click the progress link to go to Azure Portal

**Expected behavior**
I'd expect that if the link to view progress is being shown in the terminal that the link is functional and shows me progress. Perhaps I clicked the link "too early" in the provisioning process but the provision output shows me that resources were already created on my behalf.

If there's some expected latency here, we should consider showing this link later or maybe not at all.

**Environment**
Information on your environment:
- WS- Ubuntu 20.04.4 LTS

**Additional context**
cc: @Austinauth as he's been working on provisioning output improvements

**Comment by ellismg** [comment]
> If there's some expected latency here, we should consider showing this link later or maybe not at all.

At one point this link was sort of helpful for monitoring progress (in practice it was sort of not great because most of the real deployment work happens inside the resource group, and so you have to click through from this page to access the meat of the operation.

With the work Wei and Wallace have been doing to improve the output (along with Austin's thoughts, which seems like is aligned with their thinking) maybe the link is less useful now and we should just remove it (or we could defer printing it until after the operation is complete).

We do print this link very early today, before we've even tried to hit the ARM API to fetch information about the deployment (that's what powers the progress output) and so I could imagine a case where the ARM API still gives a 404 for the deployment (so we haven't yet showed progress) and clicking the link causes you to win the race.

I would have expected, however, that if you had progress in the CLI the portal would be able to see the deployment, sort of surprised that by the time we can access the deployment object via the ARM API it's still not visible to the portal.
