### ISSUE TITLE
Replace Azure Graph calls with CLI/REST Calls?

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#540]
We have noticed two things:

1. Azure Graph API calls seem to be taking longer than expected
2. Azure Graph data seems to have a sync delay between when the resource is created in Azure and when it is available in the Azure Graph API.

Should we remove the Azure Graph calls in our main flow and replace with either REST or azcli calls?

**Comment by weikanglim** [comment]
The guaranteed SLA for azure resource graph is: 95% of all changes to be present in resource graph under 30s. There is no upper bound on delay (likely a day or a few hours). Given these constraints, and that the initial change to adopt Azure Resource Graph was claimed performance, we should switch back to ARM APIs.

**Comment by ellismg** [comment]
I think we should also explore caching some of this information locally, so we don't have to list resource groups or do other operations to "discover" resources every time the CLI boots.  It seems like after an `azd provision` we should be able to take the set of provisioned resources, query the "interesting" ones (I think this will be based on RP, for RPs we know do compute and may be tied to an azd service) and then query their tags and save a mapping, so we can quickly correlate service names to resource IDs.

For Terraform and Pulumi it's probably easier since the state file would contain all of this information.
