### ISSUE TITLE
Fetch current deplyment : deployment not found

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#657]
**Describe the issue:**
Failed when we try to run the command `azd monitor --live`

**Repro Steps:**
1. Run ` az login --use-device-code` 
2. Run `azd up -t todo-python-mongo-terraform -b staging`
3. run `azd monitor --live`

**Error Message:**
![image](https://user-images.githubusercontent.com/74638143/189913113-faa08b0e-89cd-40a8-b4f8-8d0d5a9c8550.png)

**Environment:**
Windows desktop / linnux desktop / MacOS desktop / WSL / DevContainer in VS Code / Codespaces
Template: 
1. https://github.com/Azure-Samples/todo-python-mongo-terraform
2. https://github.com/Azure-Samples/todo-nodejs-mongo-terraform

**Expected behavior:**
Run command: `azd monitor --live` can success

@jongio for notification.

**Comment by rajeshkamal5050** [comment]
Same #652 issue. @wbreza please feel free to close one.

**Comment by wbreza** [comment]
`azd montor` updates were missing during terraform development.   Right now the command queries the ARM data plan to get the recent deployments which it is unable to find since the deployment was performed by terraform. 

To resolve this issue we would need to perform the following:

1. Update command to call into provisioning manager.
1. Update `GetDeployment` method in terraform provider to query resource groups from state.
