### ISSUE TITLE
Implement `azd login` with golang `azidentity` module

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#711]
Update `azd login` command to leverage the Azure SDK Golang [azidentity module](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity)

**Comment by ellismg** [comment]
I think we'll have to end up using https://github.com/AzureAD/microsoft-authentication-library-for-go instead of identity, since we'll need to maintain a persistent token cache.  We also need to ensure this cache is properly encrypted, which will be platform specific (we can decouple that from the larger effort and start with a plaintext cache)

We'll also need to support both public and confidential clients (in the MSAL parlance) to support both logging in as user and authenticating as a service principal.

When can then implement a `TokenCredential` that uses this cache.

**Comment by ellismg** [comment]
[Here's](https://github.com/ellismg/azure-dev/tree/ellismg/add-auth) my work in progress branch.  I'm rebasing this frequently so I wouldn't encourage anyone to branch off the top of it, but you can start to get a sense for what the changes will look like.
