### ISSUE TITLE
[Issue] Use main as default branch on azd pipeline config

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#735]
All of our templates use "main" as their default branch. When we create repos on behalf of users via `azd pipeline config`,  we should use this same convention.

![image](https://user-images.githubusercontent.com/8949415/191867471-716d6d74-b9cb-4fff-b39e-cccd3e9480ca.png)

**Comment by jongio** [comment]
Can you confirm that your default git branch is main?

**Comment by vhvb1989** [comment]
possible duplicate from: https://github.com/Azure/azure-dev/issues/725

**Comment by vhvb1989** [comment]
Running `azd up` clones a template and removes the .git folder (so any branch info or remotes are lost)
Then, when running `azd pipeline config`, git is initiated using default branch `master`. 

If you manually clone a template (git checkout template-url) and run `azd pipeline config`, you will get an error when trying to push at the end because your `origin` remote would be set to Azure-Samples url repo.  So you need to create a different remote and use it as `azd pipeline config --remote-name myRepo`

**Comment by rajeshkamal5050** [comment]
Closing this in favor of
- #725
