### ISSUE TITLE
Azdo provider for pipeline config creates a new pipeline in azdo on every run

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#752]
Running `azd pipeline config` multiple times without pushing code to the repo would create multiple pipelines.

This is not a good approach because all pipelines would be triggered as soon as code is pushed to the repo.

For example, running `azd pipeline config` 3 times gave me:

![image](https://user-images.githubusercontent.com/24213737/192588090-95e27ece-17ba-4b4d-a51f-5554f3633786.png)

To be consistent with GitHub, there should only be one pipeline created.

**Comment by hattan** [comment]
This is a problem if you are running azd pipieline config multiple times. However, this was introduced specifically to address and allow multiple repos in the same project to have different pipelines. Since AzDo supports multiple repos, it is possible to have multiple azd repos in a single project each with their own pipeline.

We should check to see if there is a pipeline for the current repo and only create a new pipeline if it's a different pipeline.

**Comment by rajeshkamal5050** [comment]
Fixed duplicate pipeline creation as part of PR
- https://github.com/Azure/azure-dev/pull/757
