### ISSUE TITLE
Git push error for azdo 

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#755]
PR 743 build - 
azd version 0.2.0-beta.3-pr.1877365 (commit 33710f9beab18fc32168ae2e02768f2697bdc164)

>azd init -t Azure-Samples/todo-nodejs-mongo -b pr/743

**Scopes of PAT**
Agent Pools (read, manage)
Build (read and execute)
Code (full)
Project and team (read, write and manage)
Release (read, write, execute and manage)
Service Endpoints (read, query and manage)

```
D:\codes\test\node927>azd pipeline config --provider azdo
Using pipeline provider: Azure DevOps
You need an Azure DevOps Personal Access Token (PAT). Please create a PAT by following the instructions here https://aka.ms/azure-dev/azdo-pat
? Personal Access Token (PAT): xxx

? Personal Access Token (PAT): xxx
? Save the PAT to the node927 environment file (.env)? Yes
? Please enter an Azure DevOps Organization Name: puichan0401

? Please enter an Azure DevOps Organization Name: puichan0401
Creating or updating service principal az-dev-09-27-2022-19-45-02.

? Initialize a new git repository? Yes
? A remote named "origin" was not found. Would you like to configure one? Yes
? How would you like to configure your project? Create a new Azure DevOps Project
? Enter the name for your new Azure DevOps Project OR Hit enter to use this name: (node927)

? Enter the name for your new Azure DevOps Project OR Hit enter to use this name: node927
using default repo (node927) in newly created project(node927)
? Would you like to commit and push your local changes to start the configured CI pipeline? Yes
Pushing changes
fatal: Authentication failed for 'https://dev.azure.com/puichan0401/node927/_git/node927/'
Error: git push: pushing changes: failed to push: exit code: 128, stdout: , stderr: : exit status 128
```

I ran this again with --debug. This time, I am prompted for credential. A new PAT entry is added:
![image](https://user-images.githubusercontent.com/8701892/192624002-8608ba33-6203-409f-a132-7c3bd5fba727.png)

**End of the debug output** 
...
```
Service Connection azconnection already exists. Updating endpoint
? Would you like to commit and push your local changes to start the configured CI pipeline? Yes
2022/09/27 12:54:54 command_runner.go:95: Run exec: 'git -C D:\codes\test\node927 branch --show-current'
2022/09/27 12:54:54 command_runner.go:95: Run exec: 'git config credential.helper'
2022/09/27 12:54:54 command_runner.go:95: Run exec: 'git -C D:\codes\test\node927 add .'
2022/09/27 12:54:54 command_runner.go:95: Run exec: 'git -C D:\codes\test\node927 commit --allow-empty -m Configure Azure Developer Pipeline'
Pushing changes
2022/09/27 12:54:54 command_runner.go:95: Run exec: 'git -C D:\codes\test\node927 push --set-upstream origin main'
Enumerating objects: 182, done.
Counting objects: 100% (182/182), done.
Delta compression using up to 8 threads
Compressing objects: 100% (170/170), done.
Writing objects: 100% (182/182), 685.24 KiB | 7.29 MiB/s, done.
Total 182 (delta 19), reused 0 (delta 0), pack-reused 0
remote: Analyzing objects... (182/182) (48 ms)
remote: Storing packfile... done (91 ms)
remote: Storing index... done (35 ms)
To https://dev.azure.com/puichan0401/node927/_git/node927
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.
2022/09/27 12:55:06 command_runner.go:95: Run exec: 'git -C D:\codes\test\node927 remote set-url origin https://puichan0401@dev.azure.com/puichan0401/node927/_git/node927'

Successfully configured Azure DevOps Repository https://dev.azure.com/puichan0401/node927/_git/node927

Error: post git push hook: Could not queue the build because there were validation errors or warnings.
```

Just checked the project. After running `azd pipeline config --debug` (and I suspect with the Git PAT),  
-  code is pushed and
- pipeline run is a success!

Not sure why the "Error: post git push hook: Could not queue the build because there were validation errors or warnings."

**Comment by vhvb1989** [comment]
Removed the `blocker` label from this issue.

The root cause is related to how git credentials are persisted and not related to azd.

Uses must be aware than rotating a PAT would affect any store credentials using that PAT, so they need to refresh the stores.

We can invest some time in the future on how to provide good error handling or messages about wrong PAT

**Comment by v-jiaodi** [comment]
We also encounter the same issue on **Mac OS**, but we created a `master`  branch to push code, and it passes.

**Comment by puicchan** [comment]
@vhvb1989 what if I work on multiple repo and use diff PAR for my projects? This is not about rotating PAT. Previous credential is cached. How do we prevent that?

**Comment by vhvb1989** [comment]
> what if I work on multiple repo and use diff PAR for my projects?

git-credential-manager automatically stores one credential per domain.  This is because you would use the same PAT for all the projects/repos/pipelines within an Azdo Server. The PAT can't not be scoped to one project or repo only, as it is created for the entire Organization (or even across organizations).

The PAT is equivalent to your user-log-in credentials. You don't need a different user-account for each project.  

Using one PAT per repo (within the same organization) is equivalent to have multiple user accounts (one account per repo)

It is more likely to think about a relation between a PAT and a tool.  You might have one PAT for different tools. For example, one PAT for `azd cli`, another PAT for `az cli`, another PAT for some scripts, etc.  Then you can control the access that each tool can have with the PAT.
The PAT is usually regenerated or expired when the tool is no longer in use, or after a time period.  After that, people usually know that they need to update the PAT for that tool
