### ISSUE TITLE
[Issue] 404 Not Found failed setting AZURE_CREDENTIALS on pipeline config

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#820]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.3.0-beta.1 (commit c5344160ed49bfda75281fba28b5e9ac7b96670e)

**Output from `az version`** 
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}

**Describe the bug**
Getting a 404 on running azd pipeline config

**To Reproduce**
1. Run azd up on todo-python-mongo
2. Run pipeline config 
![image](https://user-images.githubusercontent.com/8949415/194164489-06bab650-76e3-4a97-96c3-48710621182b.png)

**Environment**
Information on your environment:
    * IDE and version : VSCode 1.71.2

**Additional context**
Tried again after running az login and gh login and it was still not working.

**Comment by vhvb1989** [comment]
Hey @savannahostrowski , 

I am curious to know how did you get the template?  Did you use `azd` to select and donwload the template?

The reason I am asking is because, according to the image evidence, `azd` did not offer you to create a new Git Repository. Instead, it looks like `azd` detected a git `origin` within the folder pointing to the repo: 

https://github.com/savannahostrowski/gh-universe

Is this a private repo?  ( since following the link is a 404 not found error)

In order to fix this issue, remove the `remote` record from your local git repo, running:
`git remote remove origin`

Then run `azd pipeline config` again.  This time `azd` won't find the `origin` remote and it will guide you to create it.

let me know how it goes
