### ISSUE TITLE
`azd pipeline config` - device is required to be managed to access this resource

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#866]
**Describe the issue:**
Failed when we try to run the command `azd pipeline config` and `azd pipeline config --provider azdo`

Besides, it is a similar error with https://github.com/Azure/azure-dev/issues/768.

**Repro Steps:**
1. Run `azd login`
2. Run `bash ./test-templates.sh -t Azure-Sample/todo-nodejs-mongo-swa-func -b pr/551 -c false`
3. Run `azd pipeline config` or `azd pipeline config --provider azdo`

**Error Message:**
![image](https://user-images.githubusercontent.com/74638143/195049004-e1e21ba7-4d84-4669-add2-0d9843b0a0cd.png)

**Environment:**
OS: DevContainer in VS Code 
Template: 
https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func
https://github.com/Azure-Samples/todo-python-mongo-swa-func

**Expected behavior:**
Run command: `azd pipeline config` and `azd pipeline config --provider azdo` can success

@jongio  for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you triage this? Seeing similar issues often. Why are folks running into it. Any fixes or improvements on docs we could make?

**Comment by vhvb1989** [comment]
This is not really an `azd` issue.

Explanation:
[Conditional Access policy](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-policies) can be set up for Azure subscriptions.  When this policy is enabled for a tenant (Azure Subscription), there are specific rules which determine the min requirements for logging in to the Azure Subscription (or to specific operations/areas within the subscription)

In this case, @hongli750210, you are trying to log in to an Azure subscription and access the Active Directory operations (to create Service Principals) which requires that the device that is used to login to Azure is managed by the Tenant.  An example of this is the Microsoft tenant.  If you want to login with your Microsoft account to the Azure portal (requires Active directory), you first need to enroll/register your device/computer/browser-session with your tenant, so it becomes managed by the Organization.

In order to fix this, make sure that you can log in to Azure with the device you are using.
For example, if you are using `DevContainer in VS Code`, it means you might be running a Linux distribution with docker and connecting VSCode to it.
Run a browser from the container and try to access the Azure Portal with your account. That would validate the device and enroll/register it to Azure Tenant

I will try to see if we can do any changes to the container to support this.
If not, we should document that `azd pipeline config` is not supported from the devContainer

**Comment by zedy-wj** [comment]
@vhvb1989 

1. After investigating, we found that `azd` detects it's in `devcontainer` and logs in with `--use-device-code`. About this issue, we can run a browser from the container through the `az login` method. After testing, the issue is no longer reproduced, do you think this way is feasible, or do you have the other way?

2. Back to the way of logging in with the `--use-device-code`, there are currently two environments that use this way to log in.

- Devcontainer: After failing to execute `azd pipeline config`, we can run `az login --scope https://graph.microsoft.com//.default` to re-authenticate, and tests can pass.
- Codespace: When we run the command above, but it can not re-authenticate successfully. 

3. For the Linux `Ubuntu 20.04` environment: At present, the two login methods of `az login` and `az login --use-device-code` will have the error message: `device is required to be managed to access this resource` when executing `azd pipeline config`.

Do you have any ideas to fix this issue in `codespace` and `Linux` environment?

**Comment by vhvb1989** [comment]
> Do you have any ideas to fix this issue in codespace and Linux environment?

Please skip this environments for now.  We need to make `azd` to return an error and mention that `pipeline config` is not supported for those configurations.

Until that is done, please skip those scenarios from `pipeline config` tests to unblock

**Comment by rajeshkamal5050** [comment]
@puicchan @vhvb1989 can we also add this to the known issues?

**Comment by rajeshkamal5050** [comment]
Removing blocker for this one. Since it is getting tracked under,
- https://github.com/Azure/azure-dev/issues/957 which is a blocker for the release.

**Comment by puicchan** [comment]
Hannah has added to Dev Hub.
