### ISSUE TITLE
[Issue]VS Code report issue button brings you to a 404

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#927]
I'll file a bug for how this occurred but the link that this "Report an issue" button brings you to is a 404

![image](https://user-images.githubusercontent.com/8949415/196817272-792c3415-348a-4925-9b33-f2f73c4fff5f.png)

Link: https://github.com/Microsoft/azure-dev/issues/new?body=The%20issue%20text%20was%20copied%20to%20the%20clipboard.%20%20Please%20paste%20it%20into%20this%20window.

**Comment by rajeshkamal5050** [comment]
Looks like the link is broken. Should change **_Microsoft_** to **_Azure_** in the URL.

**Comment by philliphoff** [comment]
The common library that manages telemetry and error reporting assumes by default that its extensions exist within the `microsoft` org, if not told otherwise.  I've filed an issue for [that](https://github.com/microsoft/vscode-azuretools/issues/1256) as that may not be the best default logic, but we can also just be specific and set the `bugs` URL in `package.json`.
