### ISSUE TITLE
[Issue]  503 when running up on template with func

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#932]
I'm seeing this when running up on a template with func in it.  I think it is because we try to deploy to a function before the zip deploy endpoint is ready.  

I believe we need to have a retry here.

```
Error: deploying service: deploying service api package: POST https://func-api-rwhhjrs4jzmkg.scm.azurewebsites.net/api/zipdeploy
--------------------------------------------------------------------------------
RESPONSE 503: 503 Site Unavailable
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
The service is unavailable.
--------------------------------------------------------------------------------
```

**Comment by rajeshkamal5050** [comment]
Also, since the previous **_provision_** step is not truly done. The subsequent deploys are failing since the services are not fully up and running yet.
- It will be good if we can we also look at other **_deploy_** scenarios/hosts which might potentially return 5XX error codes for adding retries.
- It will also be good to look at how we can add post-validations to the **_provision_** step and fail provision if the post-validations don't succeed.

For such deploy operations, it will be good to have such abstractions as part of the Go SDK itself.

**Comment by rajeshkamal5050** [comment]
Is the below fix good enough or should we make additional fixes across different deployment types?

- https://github.com/Azure/azure-dev/pull/1051

**Comment by jongio** [comment]
I have not seen this issue since that fix was implemented.  Will close and reopen if we see it again.
