### ISSUE TITLE
[Issue] .zip file appears in files during azd up in a Codespace

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#947]
During azd up in a Codespace, there's a temporary file (the zipped project? for deployment maybe?) that appears in your project files. It does disappear once the deployment happens but is this intentional? A bug?

![image](https://user-images.githubusercontent.com/8949415/197236968-a0d2a2aa-b3e9-46fd-9920-30fcbc10e35b.png)

**Comment by vhvb1989** [comment]
The best thing would be probably to use a /temp folder to hold the deployment .zip file.   

But, yes, this is somehow expected @savannahostrowski 

Also adding @wbreza for feedback.

At the end, is it too bad to see this temporally zip file there @savannahostrowski ?

**Comment by savannahostrowski** [comment]
I figured that this might be expected. Honestly, this temporary file is inconsequential as it resolves as soon as the deployment is completed. I feel like for polish, it'd be nice to have a `temp/` folder store this file but this is a non-blocking item for shipping Codespaces IMO.

**Comment by ellismg** [comment]
I think the only place we ever create a zip file today is done via:

https://github.com/Azure/azure-dev/blob/d4ef68d2c5d70fb23d21e06e6c2583abc96f0954/cli/azd/pkg/project/internal/project_utils.go#L15-L36

This is called by the App Service and Functions targets, to create the zip file that we can deploy.  In the past we had to materialize this file to disk because we had to pass a path to the `az` CLI in order to do the deployment (since it only accepted file paths).

Since @wbreza rewrote our Zip Deployment logic in https://github.com/Azure/azure-dev/pull/883 we should now no longer need to materialize this file to disk if we didn't want to.  Instead, we could allocate a bytes.Buffer{} and then use that as the destination stream to write the zip file to, and then use that as what we stream as the body of our zip deployment request.

I don't, however, understand how the above name is being generated.  Maybe that's something specific to codespaces?  It does seem weird that the name doesn't match the pattern of anything we generate.

**Comment by danieljurek** [comment]
@danieljurek -- Please re-verify this from `daily`

**Comment by danieljurek** [comment]
I was able to get a file to appear when deploying the `web` service. It appears to be of the format `.\<guid>-app.zip` ... The `.\` is part of the filename which means it's "hidden" in Linux. 

The tool which generates this is part of the `swa` toolchain.

**Comment by savannahostrowski** [comment]
I actually haven't seen this repro in awhile, closing for now
